; Generated by suhc (the suihan compiler)
; Target: x86_64, NASM syntax, freestanding
; Assemble: nasm -f elf64 -o kernel.o kernel.asm
;
; Kind → hardware mapping:
;   ξ  (identity)  → .rodata (immutable, ROM-safe)
;   ζ  (shape)     → computed at runtime (never stored)
;   x  (variable)  → .bss / registers (mutable)
;   R.k (operator) → .text (instruction stream)
;   ω  (output)    → framebuffer / port I/O (terminal)
;   ΔR.k (cast)    → documented, not emitted

[bits 64]

section .rodata
; === ξ (identity) — immutable constants ===

; ξ kernel_name — identity (immutable)
kernel_name:  db "Mongwu", 0

; ξ kernel_version — identity (immutable)
kernel_version:  db "0.1.0", 0

; ξ vga_base — identity (immutable)
vga_base:  equ 753664

; ξ vga_width — identity (immutable)
vga_width:  equ 80

; ξ vga_height — identity (immutable)
vga_height:  equ 25

; ξ vga_white_on_black — identity (immutable)
vga_white_on_black:  equ 15

; dimension process_state
running:  equ 0
ready:  equ 1
blocked:  equ 2
terminated:  equ 3

; dimension privilege_level
kernel:  equ 0
user:  equ 1

; === string literals ===
__str_0:  db "Mongwu", 0
__str_1:  db "0.1.0", 0

section .data
; === songqiao — runtime configuration ===

; songqiao hardware — runtime configuration
hardware_video_base:  equ 753664
hardware_page_size:  equ 4096
hardware_stack_size:  equ 16384

; songqiao machine — runtime configuration
machine_board:  db "Ironman_SK", 0
machine_bios:  db "Insyde_V1.49", 0
machine_cpu_model:  db "i5_8250U", 0
machine_cpu_cores:  equ 4
machine_cpu_threads:  equ 8
machine_cpu_clock_mhz:  equ 1800
machine_l2_cache_kb:  equ 1024
machine_l3_cache_kb:  equ 6144
machine_ram_total_mb:  equ 16384
machine_ram_slot_a_mb:  equ 8192
machine_ram_slot_b_mb:  equ 8192
machine_ram_speed_mhz:  equ 1600
machine_gpu_discrete:  db "MX150", 0
machine_gpu_discrete_vram_mb:  equ 2048
machine_gpu_integrated:  db "UHD620", 0
machine_gpu_integrated_vram_mb:  equ 1024
machine_display_width:  equ 1920
machine_display_height:  equ 1080
machine_disk_model:  db "CT1000P3SSD8", 0
machine_disk_size_gb:  equ 932
machine_wifi:  db "AC3168", 0
machine_ethernet:  db "Realtek", 0
machine_audio:  db "Realtek_HD", 0

section .bss
; === x (variable) — mutable runtime state ===

section .text
; === R.k (operator) — instruction stream ===

; meihua vga_offset — pure computation
global vga_offset
vga_offset:
    call vga_base
    push rax
    call y
    push rax
    mov rax, 160
    mov rbx, rax
    pop rax
    imul rax, rbx
    mov rbx, rax
    pop rax
    add rax, rbx
    push rax
    call x
    push rax
    mov rax, 2
    mov rbx, rax
    pop rax
    imul rax, rbx
    mov rbx, rax
    pop rax
    add rax, rbx
    ret

; zhulin vga_putchar — control flow
global vga_putchar
vga_putchar:
    call x
    mov rdi, rax
    call y
    mov rsi, rax
    call vga_offset
    ret

; zhulin kernel_main — control flow
global kernel_main
kernel_main:
    mov rax, 77
    mov rdi, rax
    mov rax, 0
    mov rsi, rax
    mov rax, 0
    mov rdx, rax
    mov rax, 15
    mov rcx, rax
    call vga_putchar
    mov rax, 111
    mov rdi, rax
    mov rax, 1
    mov rsi, rax
    mov rax, 0
    mov rdx, rax
    mov rax, 15
    mov rcx, rax
    call vga_putchar
    mov rax, 110
    mov rdi, rax
    mov rax, 2
    mov rsi, rax
    mov rax, 0
    mov rdx, rax
    mov rax, 15
    mov rcx, rax
    call vga_putchar
    mov rax, 103
    mov rdi, rax
    mov rax, 3
    mov rsi, rax
    mov rax, 0
    mov rdx, rax
    mov rax, 15
    mov rcx, rax
    call vga_putchar
    mov rax, 119
    mov rdi, rax
    mov rax, 4
    mov rsi, rax
    mov rax, 0
    mov rdx, rax
    mov rax, 15
    mov rcx, rax
    call vga_putchar
    mov rax, 117
    mov rdi, rax
    mov rax, 5
    mov rsi, rax
    mov rax, 0
    mov rdx, rax
    mov rax, 15
    mov rcx, rax
    call vga_putchar
    ret
