; Generated by suhc (the suihan compiler)
; Target: x86_64, NASM syntax, freestanding
; Assemble: nasm -f elf64 -o kernel.o kernel.asm
;
; Kind → hardware mapping:
;   ξ  (identity)  → .rodata (immutable, ROM-safe)
;   ζ  (shape)     → computed at runtime (never stored)
;   x  (variable)  → .bss / registers (mutable)
;   R.k (operator) → .text (instruction stream)
;   ω  (output)    → framebuffer / port I/O (terminal)
;   ΔR.k (cast)    → documented, not emitted

[bits 64]

section .rodata
; === ξ (identity) — immutable constants ===

; ξ page_size — identity (immutable)
page_size:  equ 4096

; ξ kernel_start — identity (immutable)
kernel_start:  equ 0x0

; ξ kernel_end — identity (immutable)
kernel_end:  equ 0x100000

; ξ bitmap_start — identity (immutable)
bitmap_start:  equ 0x200000

; ξ vga_base — identity (immutable)
vga_base:  equ 0xB8000

; ξ vga_end — identity (immutable)
vga_end:  equ 0xBFFFF

; dimension page_state
free:  equ 0
allocated:  equ 1
reserved:  equ 2
kernel_page:  equ 3

section .data
; === songqiao — runtime configuration ===

; songqiao memory_layout — runtime configuration
memory_layout_mem_total:  equ 17179869184
memory_layout_page_count:  equ 4194304
memory_layout_bitmap_bytes:  equ 524288
memory_layout_reserved_end:  equ 0x100000
memory_layout_bitmap_addr:  equ 0x200000

section .bss
; === x (variable) — mutable runtime state ===

section .text
; === R.k (operator) — instruction stream ===

; meihua page_to_addr — pure computation
global page_to_addr
page_to_addr:
    call index
    push rax
    mov rax, 4096
    mov rbx, rax
    pop rax
    imul rax, rbx
    ret

; meihua addr_to_page — pure computation
global addr_to_page
addr_to_page:
    call addr
    push rax
    mov rax, 4096
    mov rbx, rax
    pop rax
    xor rdx, rdx
    idiv rbx
    ret

; meihua bitmap_byte — pure computation
global bitmap_byte
bitmap_byte:
    call index
    push rax
    mov rax, 8
    mov rbx, rax
    pop rax
    xor rdx, rdx
    idiv rbx
    ret

; meihua bitmap_bit — pure computation
global bitmap_bit
bitmap_bit:
    call index
    push rax
    call index
    push rax
    mov rax, 8
    mov rbx, rax
    pop rax
    xor rdx, rdx
    idiv rbx
    push rax
    mov rax, 8
    mov rbx, rax
    pop rax
    imul rax, rbx
    mov rbx, rax
    pop rax
    sub rax, rbx
    ret

; meihua total_pages — pure computation
global total_pages
total_pages:
    call mem_bytes
    push rax
    mov rax, 4096
    mov rbx, rax
    pop rax
    xor rdx, rdx
    idiv rbx
    ret

; meihua bitmap_size — pure computation
global bitmap_size
bitmap_size:
    call page_count
    push rax
    mov rax, 7
    mov rbx, rax
    pop rax
    add rax, rbx
    push rax
    mov rax, 8
    mov rbx, rax
    pop rax
    xor rdx, rdx
    idiv rbx
    ret

; zhulin mem_init — control flow
global mem_init
mem_init:
    call mem_total
    mov rdi, rax
    call total_pages
    mov rdi, rax
    call bitmap_size
    ret

; zhulin page_alloc — control flow
global page_alloc
page_alloc:
    mov rax, 0
    mov rdi, rax
    call page_to_addr
    ret

; zhulin page_free — control flow
global page_free
page_free:
    call addr
    mov rdi, rax
    call addr_to_page
    ret
