; Generated by suhc (the suihan compiler)
; Target: x86_64, NASM syntax, freestanding
; Assemble: nasm -f elf64 -o kernel.o kernel.asm
;
; Kind → hardware mapping:
;   ξ  (identity)  → .rodata (immutable, ROM-safe)
;   ζ  (shape)     → computed at runtime (never stored)
;   x  (variable)  → .bss / registers (mutable)
;   R.k (operator) → .text (instruction stream)
;   ω  (output)    → framebuffer / port I/O (terminal)
;   ΔR.k (cast)    → documented, not emitted

[bits 64]

section .rodata
; === ξ (identity) — immutable constants ===

; ξ max_processes — identity (immutable)
max_processes:  equ 16

; ξ stack_pages — identity (immutable)
stack_pages:  equ 4

; ξ pcb_size — identity (immutable)
pcb_size:  equ 160

; ξ quantum_ms — identity (immutable)
quantum_ms:  equ 50

; ξ pit_frequency — identity (immutable)
pit_frequency:  equ 1193182

; ξ timer_vector — identity (immutable)
timer_vector:  equ 32

; dimension process_state
running:  equ 0
ready:  equ 1
blocked:  equ 2
terminated:  equ 3

section .data
; === songqiao — runtime configuration ===

; songqiao scheduler_config — runtime configuration
scheduler_config_quantum_ms:  equ 50
scheduler_config_max_processes:  equ 16
scheduler_config_stack_pages:  equ 4
scheduler_config_pit_hz:  equ 20

section .bss
; === x (variable) — mutable runtime state ===

section .text
; === R.k (operator) — instruction stream ===

; projection scheduler_action — ζ-computation
global scheduler_action
scheduler_action:
    ; input in rdi, output in rax
    cmp rdi, running
    jne .proj_skip_0
    mov rax, __str_0       ; "context_switch"
    ret
.proj_skip_0:
    cmp rdi, ready
    jne .proj_skip_1
    mov rax, __str_1       ; "dispatch"
    ret
.proj_skip_1:
    cmp rdi, blocked
    jne .proj_skip_2
    mov rax, __str_2       ; "skip"
    ret
.proj_skip_2:
    cmp rdi, terminated
    jne .proj_skip_3
    mov rax, __str_3       ; "reclaim"
    ret
.proj_skip_3:
    xor rax, rax
    ret

; meihua next_pid — pure computation
global next_pid
next_pid:
    call current
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    push rax
    call count
    mov rbx, rax
    pop rax
    cmp rax, rbx
    sete al
    movzx rax, al
    test rax, rax
    jz .else_0
    mov rax, 0
    jmp .endif_0
.else_0:
    call current
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
.endif_0:
    ret

; meihua pcb_address — pure computation
global pcb_address
pcb_address:
    call base
    push rax
    call pid
    push rax
    mov rax, 160
    mov rbx, rax
    pop rax
    imul rax, rbx
    mov rbx, rax
    pop rax
    add rax, rbx
    ret

; meihua pit_divisor — pure computation
global pit_divisor
pit_divisor:
    mov rax, 1193182
    push rax
    call target_hz
    mov rbx, rax
    pop rax
    xor rdx, rdx
    idiv rbx
    ret

; zhulin timer_interrupt — control flow
global timer_interrupt
timer_interrupt:
    call current_process
    mov rdi, rax
    call process_count
    mov rsi, rax
    call next_pid
    ret

; zhulin process_create — control flow
global process_create
process_create:
    call entry
    ret
