; Generated by suhc (the suihan compiler)
; Target: x86_64, NASM syntax, freestanding
; Assemble: nasm -f elf64 -o kernel.o kernel.asm
;
; Kind → hardware mapping:
;   ξ  (identity)  → .rodata (immutable, ROM-safe)
;   ζ  (shape)     → computed at runtime (never stored)
;   x  (variable)  → .bss / registers (mutable)
;   R.k (operator) → .text (instruction stream)
;   ω  (output)    → framebuffer / port I/O (terminal)
;   ΔR.k (cast)    → documented, not emitted

[bits 64]

section .rodata
; === ξ (identity) — immutable constants ===

; ξ syscall_vector — identity (immutable)
syscall_vector:  equ 128

; ξ max_syscalls — identity (immutable)
max_syscalls:  equ 8

; dimension syscall_id
sys_write:  equ 0
sys_exit:  equ 1
sys_yield:  equ 2
sys_getpid:  equ 3
sys_alloc:  equ 4
sys_free:  equ 5
sys_sleep:  equ 6
sys_time:  equ 7

section .data
; === songqiao — runtime configuration ===

; songqiao syscall_config — runtime configuration
syscall_config_int_vector:  equ 128
syscall_config_max_calls:  equ 8
syscall_config_kernel_stack_pages:  equ 2

section .bss
; === x (variable) — mutable runtime state ===

section .text
; === R.k (operator) — instruction stream ===

; projection syscall_dispatch — ζ-computation
global syscall_dispatch
syscall_dispatch:
    ; input in rdi, output in rax
    cmp rdi, sys_write
    jne .proj_skip_0
    mov rax, __str_0       ; "handle_write"
    ret
.proj_skip_0:
    cmp rdi, sys_exit
    jne .proj_skip_1
    mov rax, __str_1       ; "handle_exit"
    ret
.proj_skip_1:
    cmp rdi, sys_yield
    jne .proj_skip_2
    mov rax, __str_2       ; "handle_yield"
    ret
.proj_skip_2:
    cmp rdi, sys_getpid
    jne .proj_skip_3
    mov rax, __str_3       ; "handle_getpid"
    ret
.proj_skip_3:
    cmp rdi, sys_alloc
    jne .proj_skip_4
    mov rax, __str_4       ; "handle_alloc"
    ret
.proj_skip_4:
    cmp rdi, sys_free
    jne .proj_skip_5
    mov rax, __str_5       ; "handle_free"
    ret
.proj_skip_5:
    cmp rdi, sys_sleep
    jne .proj_skip_6
    mov rax, __str_6       ; "handle_sleep"
    ret
.proj_skip_6:
    cmp rdi, sys_time
    jne .proj_skip_7
    mov rax, __str_7       ; "handle_time"
    ret
.proj_skip_7:
    xor rax, rax
    ret

; meihua valid_syscall — pure computation
global valid_syscall
valid_syscall:
    call id
    push rax
    mov rax, 8
    mov rbx, rax
    pop rax
    ; unsupported op: <
    test rax, rax
    jz .else_0
    mov rax, 1
    jmp .endif_0
.else_0:
    mov rax, 0
.endif_0:
    ret

; meihua valid_user_addr — pure computation
global valid_user_addr
valid_user_addr:
    call addr
    push rax
    mov rax, 4194303
    mov rbx, rax
    pop rax
    ; unsupported op: >
    test rax, rax
    jz .else_1
    mov rax, 1
    jmp .endif_1
.else_1:
    mov rax, 0
.endif_1:
    ret

; zhulin syscall_entry — control flow
global syscall_entry
syscall_entry:
    mov rax, 0
    mov rdi, rax
    call valid_syscall
    ret

; zhulin syscall_return — control flow
global syscall_return
syscall_return:
    mov rax, 0
    ret
