/*
 * suhc — emit_ts.c
 * TypeScript code generation from .szh declarations.
 *
 * Emission rules derived from the kind system (§2):
 *   ξ → const object + type union (immutable)
 *   ζ → pure function (computed at render time, never stored)
 *   x → interface field (mutable runtime data)
 *   R.k → function (traversal operator)
 *   ω → return type (terminal output)
 *   ΔR.k → JSDoc comment (entropy cast documentation)
 *
 * dimension + perpendicular → branded types (dimensional error prevention)
 * dependency → interface (typed relationship)
 * projection → resolver function (ζ-computation)
 * traversal → typed function with equation documentation
 */

#include "emitter.h"
#include "compat.h"
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <stdarg.h>

/* ------------------------------------------------------------ */
/* String utilities                                              */
/* ------------------------------------------------------------ */

/* Convert snake_case to PascalCase: structural_role → StructuralRole */
static char *to_pascal(const char *snake) {
    if (!snake) return strdup("Unknown");
    size_t len = strlen(snake);
    char *out = malloc(len + 1);
    size_t j = 0;
    bool cap_next = true;
    for (size_t i = 0; i < len; i++) {
        if (snake[i] == '_') {
            cap_next = true;
        } else {
            out[j++] = cap_next ? toupper(snake[i]) : snake[i];
            cap_next = false;
        }
    }
    out[j] = '\0';
    return out;
}

/* Convert snake_case to camelCase: structural_role → structuralRole */
static char *to_camel(const char *snake) {
    if (!snake) return strdup("unknown");
    char *pascal = to_pascal(snake);
    if (pascal[0]) pascal[0] = tolower(pascal[0]);
    return pascal;
}

/* Capitalize first letter: owner → Owner */
static char *capitalize(const char *s) {
    if (!s || !*s) return strdup("");
    char *out = strdup(s);
    out[0] = toupper(out[0]);
    return out;
}

/* ------------------------------------------------------------ */
/* Header                                                        */
/* ------------------------------------------------------------ */

static void emit_header(FILE *out, const char *filename) {
    fprintf(out, "/**\n");
    fprintf(out, " * Generated by suhc (the suihan compiler) from %s\n",
            filename ? filename : "<stdin>");
    fprintf(out, " * DO NOT EDIT — regenerate from the .szh source.\n");
    fprintf(out, " *\n");
    fprintf(out, " * Kind system guarantees:\n");
    fprintf(out, " *   ξ values are immutable (const)\n");
    fprintf(out, " *   ζ values are computed (functions, never stored)\n");
    fprintf(out, " *   Perpendicular dimensions use branded types\n");
    fprintf(out, " */\n\n");
}

/* ------------------------------------------------------------ */
/* ξ → const enum                                                */
/* ------------------------------------------------------------ */

static void emit_xi_enum(FILE *out, Decl *d) {
    if (!d->name.text) return;
    Expr *val = d->as.kinded.value;
    if (!val || val->type != EXPR_ENUM) return;

    char *pascal = to_pascal(d->name.text);

    fprintf(out, "/** ξ %s — identity (immutable) */\n", d->name.text);
    fprintf(out, "export const %s = {\n", pascal);

    for (size_t i = 0; i < val->as.enumeration.count; i++) {
        const char *member = val->as.enumeration.items[i].name.text;
        if (!member) continue;
        char *cap = capitalize(member);
        fprintf(out, "  %s: '%s'", cap, member);
        if (i + 1 < val->as.enumeration.count) fprintf(out, ",");
        fprintf(out, "\n");
        free(cap);
    }

    fprintf(out, "} as const;\n");
    fprintf(out, "export type %s = typeof %s[keyof typeof %s];\n\n",
            pascal, pascal, pascal);

    free(pascal);
}

/* ξ with non-enum value — export const */
static void emit_xi_const(FILE *out, Decl *d) {
    if (!d->name.text) return;
    Expr *val = d->as.kinded.value;
    if (!val) return;

    char *name = to_camel(d->name.text);

    fprintf(out, "/** ξ %s — identity (immutable) */\n", d->name.text);

    if (val->type == EXPR_STRING) {
        /* JSON-quote the string to handle embedded quotes/backslashes/newlines */
        const char *s = val->as.string.value ? val->as.string.value : "";
        fprintf(out, "export const %s = \"", name);
        for (const char *p = s; *p; p++) {
            unsigned char c = (unsigned char)*p;
            if (c == '"')       fprintf(out, "\\\"");
            else if (c == '\\') fprintf(out, "\\\\");
            else if (c == '\n') fprintf(out, "\\n");
            else if (c == '\r') fprintf(out, "\\r");
            else if (c == '\t') fprintf(out, "\\t");
            else if (c < 0x20)  fprintf(out, "\\u%04x", c);
            else                fputc(c, out);
        }
        fprintf(out, "\" as const;\n\n");
    } else if (val->type == EXPR_NUMBER) {
        fprintf(out, "export const %s = %s as const;\n\n",
                name, val->as.number.text ? val->as.number.text : "0");
    } else if (val->type == EXPR_IDENT) {
        fprintf(out, "export const %s = '%s' as const;\n\n",
                name, val->as.ident.name ? val->as.ident.name : "");
    } else {
        fprintf(out, "// TODO: complex ξ value for '%s'\n\n", d->name.text);
    }

    free(name);
}

static void emit_xi(FILE *out, Decl *d) {
    if (d->type != DECL_KINDED_VALUE || d->kind != KIND_XI) return;
    if (!d->as.kinded.value) return;

    if (d->as.kinded.value->type == EXPR_ENUM) {
        emit_xi_enum(out, d);
    } else {
        emit_xi_const(out, d);
    }
}

/* ------------------------------------------------------------ */
/* dimension + perpendicular → branded types                     */
/* ------------------------------------------------------------ */

static void emit_dimension(FILE *out, Decl *d) {
    if (!d->name.text) return;
    char *pascal = to_pascal(d->name.text);

    fprintf(out, "/** dimension %s */\n", d->name.text);

    /* Collect member names for union type */
    Expr *members = d->as.dimension.members;
    if (members && members->type == EXPR_LIST && members->as.list.count > 0) {
        fprintf(out, "type %sValue = ", pascal);
        bool first = true;
        for (size_t i = 0; i < members->as.list.count; i++) {
            Expr *item = members->as.list.items[i];
            if (!item) continue;
            if (item->type == EXPR_IDENT && item->as.ident.name) {
                if (strcmp(item->as.ident.name, "zero") == 0) {
                    if (!first) fprintf(out, " | ");
                    fprintf(out, "null");
                    first = false;
                } else {
                    if (!first) fprintf(out, " | ");
                    fprintf(out, "'%s'", item->as.ident.name);
                    first = false;
                }
            }
        }
        fprintf(out, ";\n");
    } else if (members && members->type == EXPR_ENUM && members->as.enumeration.count > 0) {
        /* `dimension X : a | b | c` → parser emits EXPR_ENUM */
        fprintf(out, "type %sValue = ", pascal);
        bool first = true;
        for (size_t i = 0; i < members->as.enumeration.count; i++) {
            const char *m = members->as.enumeration.items[i].name.text;
            if (!m) continue;
            if (!first) fprintf(out, " | ");
            if (strcmp(m, "zero") == 0) fprintf(out, "null");
            else fprintf(out, "'%s'", m);
            first = false;
        }
        fprintf(out, ";\n");
    } else if (members && members->type == EXPR_IDENT && members->as.ident.name) {
        /* Single-member dimension, e.g. `dimension display_field : pixels` */
        fprintf(out, "type %sValue = '%s';\n", pascal, members->as.ident.name);
    } else {
        fprintf(out, "type %sValue = string | null;\n", pascal);
    }

    /* Branded type for perpendicularity enforcement */
    fprintf(out, "export type %s = %sValue & { readonly __brand: '%s' };\n\n",
            pascal, pascal, d->name.text);

    free(pascal);
}

static void emit_perpendicular(FILE *out, Decl *d) {
    fprintf(out, "// perpendicular");
    for (size_t i = 0; i < d->as.relation.count; i++) {
        if (d->as.relation.names[i].text) {
            fprintf(out, " %s", d->as.relation.names[i].text);
            if (i + 1 < d->as.relation.count) fprintf(out, ",");
        }
    }
    fprintf(out, "\n");
    fprintf(out, "// Branded types above prevent cross-dimensional substitution.\n");
    fprintf(out, "// %s cannot be passed where %s is expected.\n\n",
            d->as.relation.count > 0 && d->as.relation.names[0].text ?
                d->as.relation.names[0].text : "?",
            d->as.relation.count > 1 && d->as.relation.names[1].text ?
                d->as.relation.names[1].text : "?");
}

/* ------------------------------------------------------------ */
/* ζ → computed function                                         */
/* ------------------------------------------------------------ */

static void emit_zeta(FILE *out, Decl *d) {
    if (d->type != DECL_KINDED_VALUE || d->kind != KIND_ZETA) return;
    if (!d->name.text) return;

    char *fn_name = to_camel(d->name.text);
    char *fn_resolve = malloc(strlen(fn_name) + 10);
    sprintf(fn_resolve, "resolve%s", to_pascal(d->name.text));

    fprintf(out, "/** ζ %s — shape (computed at render time, never stored) */\n",
            d->name.text);

    /* If the value is a projection(...) call, extract args as params */
    Expr *val = d->as.kinded.value;
    if (val && val->type == EXPR_CALL && val->as.call.callee) {
        fprintf(out, "export function %s(\n", fn_resolve);
        for (size_t i = 0; i < val->as.call.arg_count; i++) {
            Expr *arg = val->as.call.args[i];
            const char *arg_name = "unknown";
            if (arg && arg->type == EXPR_IDENT && arg->as.ident.name) {
                arg_name = arg->as.ident.name;
            }
            char *camel = to_camel(arg_name);
            fprintf(out, "  %s: string", camel);
            if (i + 1 < val->as.call.arg_count) fprintf(out, ",");
            fprintf(out, "\n");
            free(camel);
        }
        fprintf(out, "): string {\n");
        fprintf(out, "  // TODO: projection body — generate from cases\n");
        fprintf(out, "  return %s;\n",
                val->as.call.arg_count > 0 ? "structuralRole" : "''");
        fprintf(out, "}\n\n");
    } else {
        /* Simple ζ — getter function */
        fprintf(out, "export function %s(context: unknown): string {\n",
                fn_resolve);
        fprintf(out, "  // TODO: compute from context\n");
        fprintf(out, "  return '';\n");
        fprintf(out, "}\n\n");
    }

    free(fn_name);
    free(fn_resolve);
}

/* ------------------------------------------------------------ */
/* x → interface fields (collected, not emitted standalone)      */
/* ------------------------------------------------------------ */

/* x-kinded values are collected into interfaces by dependency emitter.
 * Standalone x declarations become exported mutable variables. */
static void emit_x(FILE *out, Decl *d) {
    if (d->type != DECL_KINDED_VALUE || d->kind != KIND_X) return;
    if (!d->name.text) return;

    char *camel = to_camel(d->name.text);
    Expr *val = d->as.kinded.value;

    fprintf(out, "/** x %s — variable (mutable runtime data) */\n",
            d->name.text);

    if (val && val->type == EXPR_IDENT && val->as.ident.name) {
        /* Type hint from value */
        if (strcmp(val->as.ident.name, "magnitude") == 0) {
            fprintf(out, "export type %sType = number;\n\n",
                    to_pascal(d->name.text));
        } else if (strcmp(val->as.ident.name, "text") == 0) {
            fprintf(out, "export type %sType = string;\n\n",
                    to_pascal(d->name.text));
        } else if (strcmp(val->as.ident.name, "time") == 0) {
            fprintf(out, "export type %sType = string; // ISO 8601\n\n",
                    to_pascal(d->name.text));
        } else {
            fprintf(out, "export type %sType = unknown; // %s\n\n",
                    to_pascal(d->name.text), val->as.ident.name);
        }
    } else {
        fprintf(out, "export type %sType = unknown;\n\n",
                to_pascal(d->name.text));
    }

    free(camel);
}

/* ------------------------------------------------------------ */
/* unit → type alias                                             */
/* ------------------------------------------------------------ */

static void emit_unit(FILE *out, Decl *d) {
    if (!d->name.text) return;
    char *pascal = to_pascal(d->name.text);

    /*
     * Component scaffold detection (Phase 7: constitutional renderer foundation).
     * Units whose names end in _screen are component xi-types.
     * They emit a React scaffold interface + hook declaration order.
     * Units whose names start with use_ are implementation unit hooks.
     * They emit typed hook interfaces.
     */
    size_t nlen = strlen(d->name.text);
    int is_screen = (nlen > 7 && strcmp(d->name.text + nlen - 7, "_screen") == 0);
    int is_hook   = (nlen > 4 && strncmp(d->name.text, "use_", 4) == 0);

    if (is_screen) {
        /* Component scaffold: interface + hook declaration order comment */
        fprintf(out, "/**\n");
        fprintf(out, " * Component scaffold: %s\n", d->name.text);
        fprintf(out, " * Constitutional renderer: hooks are keyed by xi-type field name.\n");
        fprintf(out, " * Call order is declaration order (structurally enforced).\n");
        fprintf(out, " */\n");
        fprintf(out, "export interface %sProps {\n", pascal);
        fprintf(out, "  readonly id: number;\n");
        fprintf(out, "}\n");
        fprintf(out, "// Hook declaration order for %s:\n", d->name.text);
        fprintf(out, "// 1. useAdminVisibility (tier, canSee)\n");
        fprintf(out, "// 2. usePermissionGate (role, canAccess)\n");
        fprintf(out, "// 3. Data hooks (keyed by xi-type)\n");
        fprintf(out, "// 4. Derived state (computed from hooks, never captured)\n\n");
    } else if (is_hook) {
        /* Implementation unit hook: typed interface */
        fprintf(out, "/**\n");
        fprintf(out, " * Implementation unit hook: %s\n", d->name.text);
        fprintf(out, " * Constitutional primitive (Build Discipline #25).\n");
        fprintf(out, " */\n");
        fprintf(out, "export interface %sReturn {\n", pascal);
        fprintf(out, "  readonly loading: boolean;\n");
        fprintf(out, "}\n\n");
    } else {
        /* Standard unit */
        fprintf(out, "/** unit %s */\n", d->name.text);
        fprintf(out, "export interface %s {\n", pascal);
        fprintf(out, "  readonly id: number;\n");
        fprintf(out, "}\n\n");
    }

    free(pascal);
}

/* ------------------------------------------------------------ */
/* dependency → interface                                        */
/* ------------------------------------------------------------ */

static void emit_dependency_ts(FILE *out, Decl *d) {
    if (!d->name.text) return;
    char *pascal = to_pascal(d->name.text);

    fprintf(out, "/** dependency %s", d->name.text);
    if (d->as.dependency.relation) {
        Expr *rel = d->as.dependency.relation;
        if (rel->type == EXPR_ARROW) {
            if (rel->as.arrow.from && rel->as.arrow.from->type == EXPR_IDENT &&
                rel->as.arrow.from->as.ident.name) {
                fprintf(out, " : %s", rel->as.arrow.from->as.ident.name);
            }
            fprintf(out, " -> ");
            if (rel->as.arrow.to && rel->as.arrow.to->type == EXPR_IDENT &&
                rel->as.arrow.to->as.ident.name) {
                fprintf(out, "%s", rel->as.arrow.to->as.ident.name);
            }
        }
    }
    fprintf(out, " */\n");
    fprintf(out, "export interface %s {\n", pascal);
    fprintf(out, "  readonly id: number;\n");

    /* Derive FK columns from the arrow expression */
    if (d->as.dependency.relation && d->as.dependency.relation->type == EXPR_ARROW) {
        Expr *rel = d->as.dependency.relation;
        if (rel->as.arrow.from && rel->as.arrow.from->type == EXPR_IDENT &&
            rel->as.arrow.from->as.ident.name) {
            const char *from = rel->as.arrow.from->as.ident.name;
            if (strcmp(from, "user") == 0) {
                fprintf(out, "  user_id: string;\n");
            } else {
                fprintf(out, "  %s_id: number;\n", from);
            }
        }
        if (rel->as.arrow.to && rel->as.arrow.to->type == EXPR_IDENT &&
            rel->as.arrow.to->as.ident.name) {
            fprintf(out, "  %s_id: number;\n", rel->as.arrow.to->as.ident.name);
        }
    }

    /* Derive fields from carries */
    for (size_t i = 0; i < d->as.dependency.field_count; i++) {
        DeclField *f = &d->as.dependency.fields[i];
        if (!f->label.text) continue;

        if (strcmp(f->label.text, "carries") == 0 && f->value) {
            /* carries: permission, label → structural_role, display_title */
            if (f->value->type == EXPR_IDENT && f->value->as.ident.name) {
                const char *name = f->value->as.ident.name;
                if (strcmp(name, "permission") == 0) {
                    fprintf(out, "  structural_role: StructuralRole;\n");
                    fprintf(out, "  role_types: string[] | null;\n");
                } else if (strcmp(name, "label") == 0) {
                    fprintf(out, "  display_title: string | null;\n");
                } else if (strcmp(name, "participation") == 0) {
                    fprintf(out, "  status: string;\n");
                } else {
                    fprintf(out, "  %s: unknown;\n", name);
                }
            }
            /* List of carries fields */
            if (f->value->type == EXPR_LIST) {
                for (size_t j = 0; j < f->value->as.list.count; j++) {
                    Expr *item = f->value->as.list.items[j];
                    if (!item || item->type != EXPR_IDENT || !item->as.ident.name)
                        continue;
                    const char *name = item->as.ident.name;
                    if (strcmp(name, "permission") == 0) {
                        fprintf(out, "  structural_role: StructuralRole;\n");
                        fprintf(out, "  role_types: string[] | null;\n");
                    } else if (strcmp(name, "label") == 0) {
                        fprintf(out, "  display_title: string | null;\n");
                    } else if (strcmp(name, "participation") == 0) {
                        fprintf(out, "  status: string;\n");
                    } else {
                        fprintf(out, "  %s: unknown;\n", name);
                    }
                }
            }
        }
    }

    fprintf(out, "  created_at: string;\n");
    fprintf(out, "}\n\n");

    free(pascal);
}

/* ------------------------------------------------------------ */
/* Expression to TypeScript string (for projection arm results)  */
/* ------------------------------------------------------------ */

/* Emit a single expression as TypeScript code into a buffer.
 * Returns a malloc'd string. */
static char *expr_to_ts(Expr *e) {
    if (!e) return strdup("undefined");

    switch (e->type) {
    case EXPR_STRING:
        if (e->as.string.value) {
            char *buf = malloc(strlen(e->as.string.value) + 4);
            sprintf(buf, "'%s'", e->as.string.value);
            return buf;
        }
        return strdup("''");

    case EXPR_IDENT:
        if (e->as.ident.name) {
            return to_camel(e->as.ident.name);
        }
        return strdup("undefined");

    case EXPR_NUMBER:
        if (e->as.number.text) return strdup(e->as.number.text);
        return strdup("0");

    case EXPR_CALL: {
        if (!e->as.call.callee) return strdup("undefined()");
        char *callee = to_camel(e->as.call.callee);
        /* Build argument list */
        size_t total_len = strlen(callee) + 3; /* callee() + null */
        char **arg_strs = malloc(e->as.call.arg_count * sizeof(char *));
        for (size_t i = 0; i < e->as.call.arg_count; i++) {
            arg_strs[i] = expr_to_ts(e->as.call.args[i]);
            total_len += strlen(arg_strs[i]) + 2; /* ", " */
        }
        char *buf = malloc(total_len + 1);
        int pos = sprintf(buf, "%s(", callee);
        for (size_t i = 0; i < e->as.call.arg_count; i++) {
            if (i > 0) pos += sprintf(buf + pos, ", ");
            pos += sprintf(buf + pos, "%s", arg_strs[i]);
            free(arg_strs[i]);
        }
        sprintf(buf + pos, ")");
        free(arg_strs);
        free(callee);
        return buf;
    }

    case EXPR_COALESCE: {
        char *left = expr_to_ts(e->as.coalesce.left);
        char *right = expr_to_ts(e->as.coalesce.right);
        char *buf = malloc(strlen(left) + strlen(right) + 8);
        sprintf(buf, "%s ?? %s", left, right);
        free(left);
        free(right);
        return buf;
    }

    case EXPR_BINARY: {
        char *left = expr_to_ts(e->as.binary.left);
        char *right = expr_to_ts(e->as.binary.right);
        const char *op = e->as.binary.op ? e->as.binary.op : "+";
        /* Handle ^ as Math.pow */
        if (strcmp(op, "^") == 0) {
            char *buf = malloc(strlen(left) + strlen(right) + 20);
            sprintf(buf, "Math.pow(%s, %s)", left, right);
            free(left); free(right);
            return buf;
        }
        /* TS operator mapping: == → ===, != → !== */
        const char *ts_op = op;
        if (strcmp(op, "==") == 0) ts_op = "===";
        else if (strcmp(op, "!=") == 0) ts_op = "!==";
        char *buf = malloc(strlen(left) + strlen(right) + strlen(ts_op) + 8);
        sprintf(buf, "%s %s %s", left, ts_op, right);
        free(left); free(right);
        return buf;
    }

    case EXPR_UNARY: {
        char *operand = expr_to_ts(e->as.unary.operand);
        const char *op = e->as.unary.op ? e->as.unary.op : "-";
        char *buf = malloc(strlen(operand) + strlen(op) + 4);
        sprintf(buf, "(%s%s)", op, operand);
        free(operand);
        return buf;
    }

    case EXPR_PIPE_CHAIN: {
        /* Emit as chained function calls: a |> b |> c → c(b(a)) */
        if (e->as.pipe_chain.count == 0) return strdup("undefined");
        char *result = expr_to_ts(e->as.pipe_chain.stages[0]);
        for (size_t i = 1; i < e->as.pipe_chain.count; i++) {
            char *fn = expr_to_ts(e->as.pipe_chain.stages[i]);
            char *buf = malloc(strlen(fn) + strlen(result) + 4);
            sprintf(buf, "%s(%s)", fn, result);
            free(fn);
            free(result);
            result = buf;
        }
        return result;
    }

    case EXPR_ARROW: {
        char *from = expr_to_ts(e->as.arrow.from);
        char *to = expr_to_ts(e->as.arrow.to);
        char *buf = malloc(strlen(from) + strlen(to) + 8);
        sprintf(buf, "%s => %s", from, to);
        free(from);
        free(to);
        return buf;
    }

    case EXPR_BLOCK: {
        /* Emit block as semicolon-separated statements */
        if (e->as.block.count == 0) return strdup("undefined");
        if (e->as.block.count == 1) return expr_to_ts(e->as.block.stmts[0]);
        size_t total = 0;
        char **parts = malloc(e->as.block.count * sizeof(char *));
        for (size_t i = 0; i < e->as.block.count; i++) {
            parts[i] = expr_to_ts(e->as.block.stmts[i]);
            total += strlen(parts[i]) + 3;
        }
        char *buf = malloc(total + 1);
        int pos = 0;
        for (size_t i = 0; i < e->as.block.count; i++) {
            if (i > 0) pos += sprintf(buf + pos, "; ");
            pos += sprintf(buf + pos, "%s", parts[i]);
            free(parts[i]);
        }
        free(parts);
        return buf;
    }

    case EXPR_WILDCARD:
        return strdup("_");

    case EXPR_MATCH: {
        /* Emit as ternary chain or switch-like expression.
         * match disc { a -> x, b -> y, _ -> z }
         * → disc === 'a' ? x : disc === 'b' ? y : z */
        char *disc = expr_to_ts(e->as.match_expr.discriminant);
        if (e->as.match_expr.arm_count == 0) {
            char *buf = malloc(strlen(disc) + 20);
            sprintf(buf, "/* match %s (empty) */", disc);
            free(disc);
            return buf;
        }

        /* Build ternary chain */
        size_t total = 256;
        char *buf = malloc(total);
        int pos = 0;

        for (size_t i = 0; i < e->as.match_expr.arm_count; i++) {
            Expr *pat = e->as.match_expr.arms[i].pattern;
            Expr *body = e->as.match_expr.arms[i].body;

            char *body_str = body ? expr_to_ts(body) : strdup("undefined");

            /* Wildcard arm → default (final else) */
            if (pat && pat->type == EXPR_WILDCARD) {
                size_t need = pos + strlen(body_str) + 4;
                if (need > total) { total = need * 2; buf = realloc(buf, total); }
                pos += sprintf(buf + pos, "%s", body_str);
                free(body_str);
                break;
            }

            char *pat_str = pat ? expr_to_ts(pat) : strdup("'?'");

            /* condition ? body : ... */
            size_t need = pos + strlen(disc) + strlen(pat_str) + strlen(body_str) + 20;
            if (need > total) { total = need * 2; buf = realloc(buf, total); }

            if (i > 0) {
                pos += sprintf(buf + pos, "\n  : ");
            }
            pos += sprintf(buf + pos, "%s === %s ? %s", disc, pat_str, body_str);
            free(pat_str);
            free(body_str);
        }

        /* If last arm wasn't a wildcard, add undefined fallback */
        if (e->as.match_expr.arm_count > 0) {
            Expr *last_pat = e->as.match_expr.arms[e->as.match_expr.arm_count - 1].pattern;
            if (!last_pat || last_pat->type != EXPR_WILDCARD) {
                size_t need = pos + 20;
                if (need > total) { total = need * 2; buf = realloc(buf, total); }
                pos += sprintf(buf + pos, "\n  : undefined");
            }
        }

        free(disc);
        return buf;
    }

    case EXPR_IF: {
        char *cond = expr_to_ts(e->as.if_expr.condition);
        char *then_b = expr_to_ts(e->as.if_expr.then_branch);
        char *else_b = expr_to_ts(e->as.if_expr.else_branch);
        char *buf = malloc(strlen(cond) + strlen(then_b) + strlen(else_b) + 16);
        sprintf(buf, "(%s) ? %s : %s", cond, then_b, else_b);
        free(cond); free(then_b); free(else_b);
        return buf;
    }

    default:
        return strdup("/* unhandled expr */");
    }
}

/* Extract patterns from a tuple expression (EXPR_LIST from parenthesized parse) */
static void extract_patterns(Expr *pattern, char ***pats, size_t *n_pats) {
    if (!pattern) {
        *pats = NULL;
        *n_pats = 0;
        return;
    }

    if (pattern->type == EXPR_LIST && pattern->as.list.count > 0) {
        *n_pats = pattern->as.list.count;
        *pats = malloc(*n_pats * sizeof(char *));
        for (size_t i = 0; i < *n_pats; i++) {
            Expr *item = pattern->as.list.items[i];
            if (item && item->type == EXPR_IDENT && item->as.ident.name) {
                (*pats)[i] = strdup(item->as.ident.name);
            } else if (item && item->type == EXPR_WILDCARD) {
                (*pats)[i] = strdup("_");
            } else if (item && item->type == EXPR_STRING && item->as.string.value) {
                (*pats)[i] = strdup(item->as.string.value);
            } else {
                (*pats)[i] = strdup("_");
            }
        }
    } else if (pattern->type == EXPR_IDENT && pattern->as.ident.name) {
        *n_pats = 1;
        *pats = malloc(sizeof(char *));
        (*pats)[0] = strdup(pattern->as.ident.name);
    } else if (pattern->type == EXPR_WILDCARD) {
        *n_pats = 1;
        *pats = malloc(sizeof(char *));
        (*pats)[0] = strdup("_");
    } else {
        *pats = NULL;
        *n_pats = 0;
    }
}

/* ------------------------------------------------------------ */
/* Dimension lookup for typed emission                           */
/* ------------------------------------------------------------ */

/* Try to find a dimension declaration matching a field name.
 * Normalizes singular/plural: structural_role ↔ structural_roles.
 * Returns the dimension Decl or NULL. */
static Decl *find_dimension_for_field(const char *field_name, Program *prog) {
    if (!field_name || !prog) return NULL;

    /* Build singular and plural forms */
    size_t flen = strlen(field_name);
    char singular[256], plural[256];
    snprintf(singular, sizeof(singular), "%s", field_name);
    snprintf(plural, sizeof(plural), "%ss", field_name);
    /* If field_name already ends in 's', singular strips it */
    if (flen > 1 && field_name[flen - 1] == 's') {
        snprintf(singular, sizeof(singular), "%.*s", (int)(flen - 1), field_name);
    }

    /* Search local declarations */
    for (size_t i = 0; i < prog->count; i++) {
        Decl *d = prog->decls[i];
        if (d->type != DECL_DIMENSION || !d->name.text) continue;
        if (strcmp(d->name.text, field_name) == 0 ||
            strcmp(d->name.text, singular) == 0 ||
            strcmp(d->name.text, plural) == 0) {
            return d;
        }
    }

    /* Search imported declarations */
    for (size_t i = 0; i < prog->count; i++) {
        Decl *d = prog->decls[i];
        if (d->type != DECL_IMPORT || !d->as.import_decl.resolved) continue;
        Program *imp = d->as.import_decl.resolved;
        for (size_t j = 0; j < imp->count; j++) {
            Decl *id = imp->decls[j];
            if (id->type != DECL_DIMENSION || !id->name.text) continue;
            if (strcmp(id->name.text, field_name) == 0 ||
                strcmp(id->name.text, singular) == 0 ||
                strcmp(id->name.text, plural) == 0) {
                return id;
            }
        }
    }

    return NULL;
}

/* Extract dimension members as a TS union type string.
 * Returns allocated string like "'owner' | 'admin' | 'member' | 'pending'"
 * or NULL if the dimension has no enum members. */
static char *dimension_to_union(Decl *dim) {
    if (!dim || dim->type != DECL_DIMENSION || !dim->as.dimension.members)
        return NULL;
    Expr *members = dim->as.dimension.members;
    if (members->type != EXPR_ENUM) return NULL;

    size_t total = 0;
    for (size_t i = 0; i < members->as.enumeration.count; i++) {
        if (members->as.enumeration.items[i].name.text)
            total += strlen(members->as.enumeration.items[i].name.text) + 6;
    }
    if (total == 0) return NULL;

    char *buf = malloc(total + 1);
    int pos = 0;
    for (size_t i = 0; i < members->as.enumeration.count; i++) {
        if (!members->as.enumeration.items[i].name.text) continue;
        if (pos > 0) pos += sprintf(buf + pos, " | ");
        pos += sprintf(buf + pos, "'%s'", members->as.enumeration.items[i].name.text);
    }
    buf[pos] = '\0';
    return buf;
}

/* ------------------------------------------------------------ */
/* projection → resolver function                                */
/* ------------------------------------------------------------ */

static void emit_projection(FILE *out, Decl *d, Program *prog) {
    if (!d->name.text) return;

    char *pascal = to_pascal(d->name.text);
    char *fn_name = malloc(strlen(pascal) + 10);
    sprintf(fn_name, "resolve%s", pascal);

    /* Extract invariant, context, yields from fields */
    const char *invariant_name = NULL;
    const char *context_name = NULL;
    const char *yields_name = NULL;

    for (size_t i = 0; i < d->as.projection.field_count; i++) {
        DeclField *f = &d->as.projection.fields[i];
        if (!f->label.text) continue;

        if (strcmp(f->label.text, "invariant") == 0) {
            if (f->value && f->value->type == EXPR_IDENT && f->value->as.ident.name)
                invariant_name = f->value->as.ident.name;
        }
        else if (strcmp(f->label.text, "context") == 0) {
            if (f->value && f->value->type == EXPR_IDENT && f->value->as.ident.name)
                context_name = f->value->as.ident.name;
        }
        else if (strcmp(f->label.text, "yields") == 0) {
            if (f->value && f->value->type == EXPR_IDENT && f->value->as.ident.name)
                yields_name = f->value->as.ident.name;
        }
    }

    /* Function signature */
    fprintf(out, "/**\n");
    fprintf(out, " * projection %s\n", d->name.text);
    fprintf(out, " * invariant × context → appearance (D12)\n");
    if (invariant_name) fprintf(out, " * invariant (ξ): %s\n", invariant_name);
    if (context_name)   fprintf(out, " * context (ζ):   %s\n", context_name);
    if (yields_name)    fprintf(out, " * yields (ω):    %s\n", yields_name);
    fprintf(out, " */\n");

    char *inv_camel = invariant_name ? to_camel(invariant_name) : strdup("input");
    char *ctx_camel = context_name ? to_camel(context_name) : strdup("context");

    /* Dimension lookup for typed emission (D12: derive type from structure) */
    Decl *inv_dim = invariant_name ? find_dimension_for_field(invariant_name, prog) : NULL;
    Decl *ctx_dim = context_name ? find_dimension_for_field(context_name, prog) : NULL;

    /* Type resolution: prefer the dimension's existing branded type (emitted
     * once by emit_dimension at file top) over re-declaring inline. Fall back
     * to dimension_to_union for dimensions that aren't in scope. */
    char *inv_union = inv_dim ? dimension_to_union(inv_dim) : NULL;
    char *ctx_union = ctx_dim ? dimension_to_union(ctx_dim) : NULL;

    char *inv_type = strdup("string");
    char *ctx_type = strdup("string");
    if (inv_dim && inv_dim->name.text) {
        /* Branded type already exported at file top — reuse it */
        free(inv_type);
        inv_type = to_pascal(inv_dim->name.text);
        free(inv_union);
        inv_union = NULL;
    } else if (inv_union) {
        char *type_name = invariant_name ? to_pascal(invariant_name) : strdup("Invariant");
        fprintf(out, "export type %s = %s;\n", type_name, inv_union);
        free(inv_type);
        inv_type = type_name;
        free(inv_union);
    }
    if (ctx_dim && ctx_dim->name.text) {
        free(ctx_type);
        ctx_type = to_pascal(ctx_dim->name.text);
        free(ctx_union);
        ctx_union = NULL;
    } else if (ctx_union) {
        char *type_name = context_name ? to_pascal(context_name) : strdup("Context");
        fprintf(out, "export type %s = %s;\n", type_name, ctx_union);
        free(ctx_type);
        ctx_type = type_name;
        free(ctx_union);
    }

    /* Check if any arm references display_title or coalesce — add optional param */
    bool needs_display_title = false;
    for (size_t i = 0; i < d->as.projection.arm_count; i++) {
        ProjectionArm *arm = &d->as.projection.arms[i];
        if (arm->body && arm->body->type == EXPR_COALESCE) {
            needs_display_title = true;
            break;
        }
    }

    fprintf(out, "export function %s(\n", fn_name);
    fprintf(out, "  %s: %s,\n", inv_camel, inv_type);
    fprintf(out, "  %s: %s", ctx_camel, ctx_type);
    if (needs_display_title) {
        fprintf(out, ",\n  displayTitle?: string | null\n");
    } else {
        fprintf(out, "\n");
    }
    fprintf(out, "): string {\n");

    free(inv_type);
    free(ctx_type);

    if (needs_display_title) {
        fprintf(out, "  if (displayTitle) return displayTitle;\n\n");
    }

    /* Emit case arms from ProjectionArm array */
    bool has_default = false;
    char *default_result = NULL;

    for (size_t i = 0; i < d->as.projection.arm_count; i++) {
        ProjectionArm *arm = &d->as.projection.arms[i];

        char **pats = NULL;
        size_t n_pats = 0;
        extract_patterns(arm->pattern, &pats, &n_pats);

        /* Check if all patterns are wildcard → this is the default case */
        bool all_wild = true;
        for (size_t j = 0; j < n_pats; j++) {
            if (strcmp(pats[j], "_") != 0) { all_wild = false; break; }
        }

        char *result_str = expr_to_ts(arm->body);

        if (all_wild && n_pats > 0) {
            has_default = true;
            default_result = result_str;
        } else {
            /* Build if-condition */
            const char *param_names[2];
            param_names[0] = inv_camel;
            param_names[1] = ctx_camel;

            fprintf(out, "  if (");
            bool first_cond = true;
            for (size_t j = 0; j < n_pats && j < 2; j++) {
                if (strcmp(pats[j], "_") == 0) continue;
                if (!first_cond) fprintf(out, " && ");
                fprintf(out, "%s === '%s'", param_names[j], pats[j]);
                first_cond = false;
            }
            fprintf(out, ") return %s;\n", result_str);
            free(result_str);
        }

        for (size_t j = 0; j < n_pats; j++) free(pats[j]);
        free(pats);
    }

    /* Default return */
    fprintf(out, "\n");
    if (has_default && default_result) {
        fprintf(out, "  return %s;\n", default_result);
        free(default_result);
    } else {
        fprintf(out, "  return %s;\n", inv_camel);
    }

    fprintf(out, "}\n\n");

    free(inv_camel);
    free(ctx_camel);
    free(fn_name);
    free(pascal);
}

/* ------------------------------------------------------------ */
/* Helper: extract body string from a traversal section body     */
/* ------------------------------------------------------------ */

static char *section_body_str(Expr *body) {
    if (!body) return strdup("");

    if (body->type == EXPR_IDENT && body->as.ident.name) {
        return strdup(body->as.ident.name);
    }
    if (body->type == EXPR_CALL && body->as.call.callee) {
        char *ts = expr_to_ts(body);
        return ts;
    }
    if (body->type == EXPR_COALESCE) {
        char *ts = expr_to_ts(body);
        return ts;
    }
    if (body->type == EXPR_BLOCK && body->as.block.count > 0) {
        /* Concatenate block statements */
        size_t total = 0;
        char **parts = malloc(body->as.block.count * sizeof(char *));
        for (size_t i = 0; i < body->as.block.count; i++) {
            parts[i] = section_body_str(body->as.block.stmts[i]);
            total += strlen(parts[i]) + 2;
        }
        char *buf = malloc(total + 1);
        size_t pos = 0;
        for (size_t i = 0; i < body->as.block.count; i++) {
            if (i > 0) { buf[pos++] = ','; buf[pos++] = ' '; }
            size_t len = strlen(parts[i]);
            memcpy(buf + pos, parts[i], len);
            pos += len;
            free(parts[i]);
        }
        buf[pos] = '\0';
        free(parts);
        return buf;
    }
    if (body->type == EXPR_STRING && body->as.string.value) {
        return strdup(body->as.string.value);
    }
    /* Fallback: use expr_to_ts */
    return expr_to_ts(body);
}

/* ------------------------------------------------------------ */
/* traversal → typed function                                    */
/* ------------------------------------------------------------ */

static void emit_traversal(FILE *out, Decl *d) {
    if (!d->name.text) return;

    /* Build function name: if already starts with "resolve_", use to_camel directly */
    char *fn_name;
    if (strncmp(d->name.text, "resolve_", 8) == 0) {
        fn_name = to_camel(d->name.text);
    } else {
        char *pascal = to_pascal(d->name.text);
        fn_name = malloc(strlen(pascal) + 10);
        sprintf(fn_name, "resolve%s", pascal);
        free(pascal);
    }

    /* Collect section labels and bodies separately */
    const char *xi_label = NULL, *zeta_label = NULL, *x_label = NULL;
    const char *rk_label = NULL, *omega_label = NULL, *delta_label = NULL;
    Expr *xi_expr = NULL, *zeta_expr = NULL, *x_expr = NULL;
    Expr *rk_expr = NULL;
    char *xi_body = NULL, *zeta_body = NULL, *x_body = NULL;
    char *rk_body = NULL, *omega_body = NULL, *delta_body = NULL;

    for (size_t i = 0; i < d->as.traversal.section_count; i++) {
        TraversalSection *sec = &d->as.traversal.sections[i];
        char *body_str = section_body_str(sec->body);

        switch (sec->section_kind) {
        case KIND_XI:
            xi_label = sec->label.text; xi_body = body_str; xi_expr = sec->body;
            break;
        case KIND_ZETA:
            zeta_label = sec->label.text; zeta_body = body_str; zeta_expr = sec->body;
            break;
        case KIND_X:
            x_label = sec->label.text; x_body = body_str; x_expr = sec->body;
            break;
        case KIND_RK:
            rk_label = sec->label.text; rk_body = body_str; rk_expr = sec->body;
            break;
        case KIND_OMEGA:
            omega_label = sec->label.text; omega_body = body_str;
            break;
        case KIND_DELTA_RK:
            delta_label = sec->label.text; delta_body = body_str;
            break;
        default: free(body_str); break;
        }
    }
    (void)rk_label; (void)delta_label; (void)omega_label; (void)xi_expr;

    /* JSDoc */
    fprintf(out, "/**\n");
    fprintf(out, " * traversal %s\n", d->name.text);
    fprintf(out, " *\n");
    if (xi_label)    fprintf(out, " * @param %s — identity (ξ)%s%s\n",
                            xi_label, xi_body && *xi_body ? ": " : "", xi_body ? xi_body : "");
    if (zeta_label)  fprintf(out, " * @param %s — context (ζ)%s%s\n",
                            zeta_label, zeta_body && *zeta_body ? ": " : "", zeta_body ? zeta_body : "");
    if (x_label)     fprintf(out, " * @param %s — data (x)%s%s\n",
                            x_label, x_body && *x_body ? ": " : "", x_body ? x_body : "");
    if (omega_label) fprintf(out, " * @returns %s (ω)\n", omega_label);
    if (delta_label) fprintf(out, " * @cast %s (ΔR.k)\n", delta_label);
    fprintf(out, " */\n");

    /* Function signature — use section LABELS as parameter names */
    fprintf(out, "export function %s(\n", fn_name);

    if (xi_label) {
        char *camel = to_camel(xi_label);
        fprintf(out, "  %s: string,\n", camel);
        free(camel);
    }
    if (zeta_label) {
        char *camel = to_camel(zeta_label);
        fprintf(out, "  %s: string,\n", camel);
        free(camel);
    }
    if (x_label) {
        char *camel = to_camel(x_label);
        fprintf(out, "  %s: unknown[],\n", camel);
        free(camel);
    }

    char *return_type = omega_label ? to_pascal(omega_label) : strdup("unknown[]");
    fprintf(out, "): %s {\n", return_type);

    /* Emit ζ computation as comment if it has a body expression */
    if (zeta_expr && zeta_body && *zeta_body) {
        char *zeta_ts = expr_to_ts(zeta_expr);
        fprintf(out, "  // ζ computed: %s\n", zeta_ts);
        free(zeta_ts);
    }

    /* Emit data fetching from x section body */
    if (x_expr) {
        char *x_ts = expr_to_ts(x_expr);
        char *x_param = x_label ? to_camel(x_label) : strdup("data");
        fprintf(out, "  const %s = %s;\n", x_param, x_ts);
        free(x_ts);
        free(x_param);
    }

    /* Emit R.k operator body — the core computation */
    if (rk_expr) {
        if (rk_expr->type == EXPR_MATCH) {
            /* Emit match as switch statement */
            char *disc = expr_to_ts(rk_expr->as.match_expr.discriminant);
            char *disc_param = to_camel(disc);
            fprintf(out, "  switch (%s) {\n", disc_param);
            for (size_t a = 0; a < rk_expr->as.match_expr.arm_count; a++) {
                Expr *pat = rk_expr->as.match_expr.arms[a].pattern;
                Expr *body = rk_expr->as.match_expr.arms[a].body;
                char *body_ts = body ? expr_to_ts(body) : strdup("undefined");
                if (pat && pat->type == EXPR_WILDCARD) {
                    fprintf(out, "    default:\n      return %s;\n", body_ts);
                } else {
                    char *pat_ts = pat ? expr_to_ts(pat) : strdup("'?'");
                    fprintf(out, "    case '%s':\n      return %s;\n", pat_ts, body_ts);
                    free(pat_ts);
                }
                free(body_ts);
            }
            fprintf(out, "  }\n");
            free(disc);
            free(disc_param);
        } else if (rk_expr->type == EXPR_BLOCK) {
            /* Block of expressions — emit as statements */
            for (size_t i = 0; i < rk_expr->as.block.count; i++) {
                char *stmt_ts = expr_to_ts(rk_expr->as.block.stmts[i]);
                if (i == rk_expr->as.block.count - 1) {
                    fprintf(out, "  return %s;\n", stmt_ts);
                } else {
                    fprintf(out, "  %s;\n", stmt_ts);
                }
                free(stmt_ts);
            }
        } else {
            /* Single expression */
            char *rk_ts = expr_to_ts(rk_expr);
            fprintf(out, "  return %s;\n", rk_ts);
            free(rk_ts);
        }
    } else if (x_label) {
        char *camel = to_camel(x_label);
        fprintf(out, "  return %s;\n", camel);
        free(camel);
    } else {
        fprintf(out, "  return [];\n");
    }

    fprintf(out, "}\n\n");

    free(fn_name);
    free(return_type);
    free(xi_body); free(zeta_body); free(x_body);
    free(rk_body); free(omega_body); free(delta_body);
}

/* ------------------------------------------------------------ */
/* morphism → type guard / transform function                    */
/* ------------------------------------------------------------ */

static void emit_morphism(FILE *out, Decl *d) {
    if (!d->name.text) return;
    char *fn_name = to_camel(d->name.text);

    fprintf(out, "/** morphism %s", d->name.text);
    if (d->as.morphism.signature) {
        Expr *sig = d->as.morphism.signature;
        if (sig->type == EXPR_ARROW) {
            if (sig->as.arrow.from && sig->as.arrow.from->type == EXPR_IDENT &&
                sig->as.arrow.from->as.ident.name) {
                fprintf(out, " : %s", sig->as.arrow.from->as.ident.name);
            }
            fprintf(out, " -> ");
            if (sig->as.arrow.to && sig->as.arrow.to->type == EXPR_IDENT &&
                sig->as.arrow.to->as.ident.name) {
                fprintf(out, "%s", sig->as.arrow.to->as.ident.name);
            }
        }
    }
    fprintf(out, " */\n");

    /* Collect preserves/changes for documentation */
    fprintf(out, "export function %s(input: Record<string, unknown>): Record<string, unknown> {\n",
            fn_name);

    for (size_t i = 0; i < d->as.morphism.field_count; i++) {
        DeclField *f = &d->as.morphism.fields[i];
        if (!f->label.text) continue;
        if (strcmp(f->label.text, "preserves") == 0) {
            fprintf(out, "  // preserves:");
            if (f->value && f->value->type == EXPR_IDENT && f->value->as.ident.name)
                fprintf(out, " %s", f->value->as.ident.name);
            fprintf(out, "\n");
        }
        if (strcmp(f->label.text, "changes") == 0) {
            fprintf(out, "  // changes:");
            if (f->value && f->value->type == EXPR_IDENT && f->value->as.ident.name)
                fprintf(out, " %s", f->value->as.ident.name);
            fprintf(out, "\n");
        }
    }

    fprintf(out, "  return { ...input }; // structure-preserving\n");
    fprintf(out, "}\n\n");

    free(fn_name);
}

/* ------------------------------------------------------------ */
/* incommensurable / commensurable — type documentation          */
/* ------------------------------------------------------------ */

static void emit_relation(FILE *out, Decl *d) {
    const char *rel = decl_type_name(d->type);
    fprintf(out, "// %s", rel);
    for (size_t i = 0; i < d->as.relation.count; i++) {
        if (d->as.relation.names[i].text) {
            fprintf(out, " %s", d->as.relation.names[i].text);
            if (i + 1 < d->as.relation.count) fprintf(out, ",");
        }
    }
    fprintf(out, "\n");
    if (d->type == DECL_INCOMMENSURABLE) {
        fprintf(out, "// These types are completely distinct — no lossless conversion.\n\n");
    } else if (d->type == DECL_COMMENSURABLE) {
        fprintf(out, "// These types share identity — lossless conversion exists.\n\n");
    }
}

/* ------------------------------------------------------------ */
/* meihua → pure function                                        */
/* ------------------------------------------------------------ */

/* Convert meihua function calls to Math.* equivalents */
static char *meihua_expr_to_ts(Expr *e) {
    if (!e) return strdup("0");

    switch (e->type) {
    case EXPR_CALL: {
        if (!e->as.call.callee) return strdup("0");
        /* Map mathematical functions to Math.* */
        const char *callee = e->as.call.callee;
        const char *math_fn = NULL;
        if (strcmp(callee, "sqrt") == 0) math_fn = "Math.sqrt";
        else if (strcmp(callee, "abs") == 0) math_fn = "Math.abs";
        else if (strcmp(callee, "floor") == 0) math_fn = "Math.floor";
        else if (strcmp(callee, "ceil") == 0) math_fn = "Math.ceil";
        else if (strcmp(callee, "round") == 0) math_fn = "Math.round";
        else if (strcmp(callee, "min") == 0) math_fn = "Math.min";
        else if (strcmp(callee, "max") == 0) math_fn = "Math.max";
        else if (strcmp(callee, "log") == 0) math_fn = "Math.log";
        else if (strcmp(callee, "sin") == 0) math_fn = "Math.sin";
        else if (strcmp(callee, "cos") == 0) math_fn = "Math.cos";
        else if (strcmp(callee, "tan") == 0) math_fn = "Math.tan";
        else if (strcmp(callee, "acos") == 0) math_fn = "Math.acos";
        else if (strcmp(callee, "asin") == 0) math_fn = "Math.asin";
        else if (strcmp(callee, "atan") == 0) math_fn = "Math.atan";
        else if (strcmp(callee, "atan2") == 0) math_fn = "Math.atan2";
        else if (strcmp(callee, "pow") == 0) math_fn = "Math.pow";

        const char *fn = math_fn ? math_fn : callee;
        size_t total_len = strlen(fn) + 3;
        char **arg_strs = malloc(e->as.call.arg_count * sizeof(char *));
        for (size_t i = 0; i < e->as.call.arg_count; i++) {
            arg_strs[i] = meihua_expr_to_ts(e->as.call.args[i]);
            total_len += strlen(arg_strs[i]) + 2;
        }
        char *buf = malloc(total_len + 1);
        int pos = sprintf(buf, "%s(", fn);
        for (size_t i = 0; i < e->as.call.arg_count; i++) {
            if (i > 0) pos += sprintf(buf + pos, ", ");
            pos += sprintf(buf + pos, "%s", arg_strs[i]);
            free(arg_strs[i]);
        }
        sprintf(buf + pos, ")");
        free(arg_strs);
        return buf;
    }
    case EXPR_BINARY: {
        char *left = meihua_expr_to_ts(e->as.binary.left);
        char *right = meihua_expr_to_ts(e->as.binary.right);
        const char *op = e->as.binary.op ? e->as.binary.op : "+";
        if (strcmp(op, "^") == 0) {
            char *buf = malloc(strlen(left) + strlen(right) + 20);
            sprintf(buf, "Math.pow(%s, %s)", left, right);
            free(left); free(right);
            return buf;
        }
        /* TS operator mapping: == → ===, != → !== */
        const char *ts_op = op;
        if (strcmp(op, "==") == 0) ts_op = "===";
        else if (strcmp(op, "!=") == 0) ts_op = "!==";
        char *buf = malloc(strlen(left) + strlen(right) + strlen(ts_op) + 8);
        sprintf(buf, "(%s %s %s)", left, ts_op, right);
        free(left); free(right);
        return buf;
    }
    case EXPR_IDENT:
        if (e->as.ident.name) return strdup(e->as.ident.name);
        return strdup("0");
    case EXPR_NUMBER:
        if (e->as.number.text) return strdup(e->as.number.text);
        return strdup("0");
    case EXPR_UNARY: {
        char *operand = meihua_expr_to_ts(e->as.unary.operand);
        const char *op = e->as.unary.op ? e->as.unary.op : "-";
        char *buf = malloc(strlen(operand) + strlen(op) + 4);
        sprintf(buf, "(%s%s)", op, operand);
        free(operand);
        return buf;
    }
    case EXPR_IF: {
        char *cond = meihua_expr_to_ts(e->as.if_expr.condition);
        char *then_b = meihua_expr_to_ts(e->as.if_expr.then_branch);
        char *else_b = meihua_expr_to_ts(e->as.if_expr.else_branch);
        char *buf = malloc(strlen(cond) + strlen(then_b) + strlen(else_b) + 16);
        sprintf(buf, "(%s) ? %s : %s", cond, then_b, else_b);
        free(cond); free(then_b); free(else_b);
        return buf;
    }
    case EXPR_COALESCE: {
        char *left = meihua_expr_to_ts(e->as.coalesce.left);
        char *right = meihua_expr_to_ts(e->as.coalesce.right);
        char *buf = malloc(strlen(left) + strlen(right) + 8);
        sprintf(buf, "(%s ?? %s)", left, right);
        free(left); free(right);
        return buf;
    }
    case EXPR_STRING: {
        const char *val = e->as.string.value ? e->as.string.value : "";
        char *buf = malloc(strlen(val) + 4);
        sprintf(buf, "'%s'", val);
        return buf;
    }
    case EXPR_LIST: {
        size_t total = 4; /* [] */
        char **items = malloc(e->as.list.count * sizeof(char *));
        for (size_t i = 0; i < e->as.list.count; i++) {
            items[i] = meihua_expr_to_ts(e->as.list.items[i]);
            total += strlen(items[i]) + 2;
        }
        char *buf = malloc(total + 1);
        int pos = sprintf(buf, "[");
        for (size_t i = 0; i < e->as.list.count; i++) {
            if (i > 0) pos += sprintf(buf + pos, ", ");
            pos += sprintf(buf + pos, "%s", items[i]);
            free(items[i]);
        }
        sprintf(buf + pos, "]");
        free(items);
        return buf;
    }
    case EXPR_MATCH: {
        /* match disc { a -> x, b -> y, _ -> z } → nested ternary */
        char *disc = meihua_expr_to_ts(e->as.match_expr.discriminant);
        /* Build from last arm (default) backward */
        char *result = NULL;
        /* Find wildcard arm for default */
        for (size_t i = 0; i < e->as.match_expr.arm_count; i++) {
            Expr *pat = e->as.match_expr.arms[i].pattern;
            if (pat && pat->type == EXPR_WILDCARD) {
                result = meihua_expr_to_ts(e->as.match_expr.arms[i].body);
                break;
            }
        }
        if (!result) result = strdup("undefined");
        /* Wrap non-wildcard arms as ternaries */
        for (int i = (int)e->as.match_expr.arm_count - 1; i >= 0; i--) {
            Expr *pat = e->as.match_expr.arms[i].pattern;
            if (pat && pat->type == EXPR_WILDCARD) continue;
            /* Pattern idents are literal match values — emit as string literals */
            char *pstr;
            if (pat && pat->type == EXPR_IDENT && pat->as.ident.name) {
                pstr = malloc(strlen(pat->as.ident.name) + 4);
                sprintf(pstr, "'%s'", pat->as.ident.name);
            } else {
                pstr = meihua_expr_to_ts(pat);
            }
            char *body = meihua_expr_to_ts(e->as.match_expr.arms[i].body);
            char *new_r = malloc(strlen(disc) + strlen(pstr) + strlen(body) + strlen(result) + 24);
            sprintf(new_r, "(%s === %s) ? %s : %s", disc, pstr, body, result);
            free(pstr); free(body); free(result);
            result = new_r;
        }
        free(disc);
        return result;
    }
    default:
        return expr_to_ts(e);
    }
}

static void emit_meihua(FILE *out, Decl *d) {
    if (!d->name.text) return;
    char *fn_name = to_camel(d->name.text);

    fprintf(out, "/** meihua %s — pure computation (no side effects) */\n",
            d->name.text);
    fprintf(out, "export function %s(", fn_name);

    for (size_t i = 0; i < d->as.exec_layer.param_count; i++) {
        if (d->as.exec_layer.params[i].text) {
            fprintf(out, "%s: number", d->as.exec_layer.params[i].text);
            if (i + 1 < d->as.exec_layer.param_count) fprintf(out, ", ");
        }
    }

    fprintf(out, "): number {\n");

    /* Emit real body if the parser captured one */
    Expr *body = d->as.exec_layer.body;
    /* Unwrap single-statement blocks */
    if (body && body->type == EXPR_BLOCK && body->as.block.count == 1) {
        body = body->as.block.stmts[0];
    }
    if (body) {
        char *ts = meihua_expr_to_ts(body);
        fprintf(out, "  return %s;\n", ts);
        free(ts);
    } else {
        fprintf(out, "  return 0; // no body captured\n");
    }

    fprintf(out, "}\n\n");

    free(fn_name);
}

/* ------------------------------------------------------------ */
/* songqiao → runtime config                                     */
/* ------------------------------------------------------------ */

static void emit_songqiao(FILE *out, Decl *d) {
    if (!d->name.text) return;
    char *camel = to_camel(d->name.text);

    fprintf(out, "/** songqiao %s — runtime landscape configuration */\n",
            d->name.text);
    fprintf(out, "export function %s(", camel);

    for (size_t i = 0; i < d->as.exec_layer.param_count; i++) {
        if (i > 0) fprintf(out, ", ");
        if (d->as.exec_layer.params[i].text) {
            fprintf(out, "%s: string", d->as.exec_layer.params[i].text);
        }
    }

    fprintf(out, "): unknown {\n");

    Expr *body = d->as.exec_layer.body;
    if (body && body->type == EXPR_BLOCK && body->as.block.count == 1) {
        body = body->as.block.stmts[0];
    }
    if (body) {
        char *ts = meihua_expr_to_ts(body);
        fprintf(out, "  return %s;\n", ts);
        free(ts);
    } else {
        fprintf(out, "  return undefined;\n");
    }

    fprintf(out, "}\n\n");
    free(camel);
}

/* ------------------------------------------------------------ */
/* ω → output type                                               */
/* ------------------------------------------------------------ */

static void emit_omega(FILE *out, Decl *d) {
    if (d->type != DECL_KINDED_VALUE || d->kind != KIND_OMEGA) return;
    if (!d->name.text) return;

    char *pascal = to_pascal(d->name.text);

    fprintf(out, "/** ω %s — output (consumed by viewer) */\n", d->name.text);
    fprintf(out, "export type %s = unknown; // TODO: derive from traversal\n\n",
            pascal);

    free(pascal);
}

/* ------------------------------------------------------------ */
/* Public API                                                    */
/* ------------------------------------------------------------ */

/* Check if an expression tree references a name (by string match) */
static bool expr_references_name(Expr *e, const char *name) {
    if (!e || !name) return false;
    switch (e->type) {
    case EXPR_IDENT:
        if (e->as.ident.name && strcmp(e->as.ident.name, name) == 0)
            return true;
        break;
    case EXPR_CALL:
        if (e->as.call.callee && strcmp(e->as.call.callee, name) == 0)
            return true;
        for (size_t i = 0; i < e->as.call.arg_count; i++)
            if (expr_references_name(e->as.call.args[i], name)) return true;
        break;
    case EXPR_BINARY:
        if (expr_references_name(e->as.binary.left, name)) return true;
        if (expr_references_name(e->as.binary.right, name)) return true;
        break;
    case EXPR_UNARY:
        if (expr_references_name(e->as.unary.operand, name)) return true;
        break;
    case EXPR_LIST:
        for (size_t i = 0; i < e->as.list.count; i++)
            if (expr_references_name(e->as.list.items[i], name)) return true;
        break;
    case EXPR_BLOCK:
        for (size_t i = 0; i < e->as.block.count; i++)
            if (expr_references_name(e->as.block.stmts[i], name)) return true;
        break;
    case EXPR_ARROW:
        if (expr_references_name(e->as.arrow.from, name)) return true;
        if (expr_references_name(e->as.arrow.to, name)) return true;
        break;
    case EXPR_COALESCE:
        if (expr_references_name(e->as.coalesce.left, name)) return true;
        if (expr_references_name(e->as.coalesce.right, name)) return true;
        break;
    case EXPR_PIPE_CHAIN:
        for (size_t i = 0; i < e->as.pipe_chain.count; i++)
            if (expr_references_name(e->as.pipe_chain.stages[i], name)) return true;
        break;
    case EXPR_IF:
        if (expr_references_name(e->as.if_expr.condition, name)) return true;
        if (expr_references_name(e->as.if_expr.then_branch, name)) return true;
        if (expr_references_name(e->as.if_expr.else_branch, name)) return true;
        break;
    default:
        break;
    }
    return false;
}

/* Check if a local declaration references an imported name.
 * This checks field labels, field values, projection arm patterns/results,
 * dependency entries, etc. Also matches singular/plural variants. */
static bool decl_references_name(Decl *d, const char *name) {
    if (!d || !name) return false;

    /* Check field values and labels */
    switch (d->type) {
    case DECL_PROJECTION:
        for (size_t f = 0; f < d->as.projection.field_count; f++) {
            DeclField *fld = &d->as.projection.fields[f];
            if (fld->value && expr_references_name(fld->value, name))
                return true;
        }
        for (size_t a = 0; a < d->as.projection.arm_count; a++) {
            ProjectionArm *arm = &d->as.projection.arms[a];
            if (expr_references_name(arm->pattern, name)) return true;
            if (expr_references_name(arm->body, name)) return true;
        }
        break;
    case DECL_DEPENDENCY:
        if (expr_references_name(d->as.dependency.relation, name)) return true;
        for (size_t f = 0; f < d->as.dependency.field_count; f++) {
            DeclField *fld = &d->as.dependency.fields[f];
            if (fld->value && expr_references_name(fld->value, name))
                return true;
        }
        break;
    case DECL_KINDED_VALUE:
        if (expr_references_name(d->as.kinded.value, name)) return true;
        break;
    case DECL_TRAVERSAL:
        for (size_t s = 0; s < d->as.traversal.section_count; s++) {
            if (expr_references_name(d->as.traversal.sections[s].body, name))
                return true;
        }
        break;
    case DECL_MEIHUA:
    case DECL_ZHULIN:
    case DECL_SONGQIAO:
        if (expr_references_name(d->as.exec_layer.body, name)) return true;
        break;
    case DECL_MORPHISM:
        if (expr_references_name(d->as.morphism.signature, name)) return true;
        for (size_t f = 0; f < d->as.morphism.field_count; f++) {
            DeclField *fld = &d->as.morphism.fields[f];
            if (fld->value && expr_references_name(fld->value, name))
                return true;
        }
        break;
    default:
        break;
    }
    return false;
}

/* Check if an imported declaration name is referenced by any local decl.
 * Also checks singular/plural variants. */
static bool is_imported_name_used(const char *imp_name, Program *local_prog) {
    for (size_t i = 0; i < local_prog->count; i++) {
        Decl *d = local_prog->decls[i];
        if (d->type == DECL_IMPORT) continue;
        if (decl_references_name(d, imp_name)) return true;
    }

    /* Also try singular/plural variants */
    size_t len = strlen(imp_name);

    /* Try appending 's' */
    char *plural = malloc(len + 2);
    sprintf(plural, "%ss", imp_name);
    for (size_t i = 0; i < local_prog->count; i++) {
        Decl *d = local_prog->decls[i];
        if (d->type == DECL_IMPORT) continue;
        if (decl_references_name(d, plural)) { free(plural); return true; }
    }
    free(plural);

    /* Try stripping trailing 's' */
    if (len > 1 && imp_name[len - 1] == 's') {
        char *singular = strndup(imp_name, len - 1);
        for (size_t i = 0; i < local_prog->count; i++) {
            Decl *d = local_prog->decls[i];
            if (d->type == DECL_IMPORT) continue;
            if (decl_references_name(d, singular)) { free(singular); return true; }
        }
        free(singular);
    }

    return false;
}

/* Emit TypeScript import statement for a resolved DECL_IMPORT.
 * Sprint 3B: only emits actually-used names from the imported module.
 * If no names are used, suppresses the import line entirely. */
static void emit_import(FILE *out, Decl *d, Program *local_prog) {
    if (!d->as.import_decl.resolved) return;

    Program *imported = d->as.import_decl.resolved;
    if (imported->count == 0) return;

    /* First pass: collect only used names */
    char *used[256];
    int n_used = 0;

    for (size_t i = 0; i < imported->count; i++) {
        Decl *id = imported->decls[i];
        if (!id->name.text) continue;
        if (id->type == DECL_IMPORT) continue;

        /* Check if this imported name is actually used locally */
        if (!is_imported_name_used(id->name.text, local_prog)) continue;

        char *name = to_pascal(id->name.text);

        /* Check for duplicates */
        int dup = 0;
        for (int s = 0; s < n_used; s++) {
            if (strcmp(used[s], name) == 0) { dup = 1; break; }
        }
        if (dup) { free(name); continue; }

        if (n_used < 256) used[n_used++] = name;
    }

    /* If no names are used, suppress import entirely */
    if (n_used == 0) return;

    fprintf(out, "import {");
    for (int i = 0; i < n_used; i++) {
        if (i > 0) fprintf(out, ",");
        fprintf(out, " %s", used[i]);
    }
    fprintf(out, " } from './%s';\n", d->as.import_decl.module_name);

    for (int i = 0; i < n_used; i++) free(used[i]);
}

/* ------------------------------------------------------------ */
/* M4: dispatch wrappers — uniform (FILE*, Decl*) signature      */
/* ------------------------------------------------------------ */

/* File-scope prog for projection dispatch wrapper */
static Program *g_ts_prog;

static void emit_kinded_value_ts(FILE *out, Decl *d) {
    switch (d->kind) {
    case KIND_XI:   emit_xi(out, d); break;
    case KIND_ZETA: emit_zeta(out, d); break;
    case KIND_X:    emit_x(out, d); break;
    case KIND_OMEGA: emit_omega(out, d); break;
    default: break;
    }
}

static void emit_projection_ts(FILE *out, Decl *d) {
    emit_projection(out, d, g_ts_prog);
}

/* M4: generated dispatch — replaces hand-written switch in emit_typescript().
 * Source of truth: ordbok/compiler/compiler_emit_ts_dispatch.szh */
#include "gen/emit_ts_dispatch.h"

/* ------------------------------------------------------------ */
/* Kind manifest — preserves kind metadata in TypeScript output  */
/* ------------------------------------------------------------ */

/* ASCII-safe kind identifier for TypeScript (avoids Unicode sigils) */
static const char *kind_id(Kind k) {
    switch (k) {
    case KIND_XI:       return "xi";
    case KIND_ZETA:     return "zeta";
    case KIND_X:        return "x";
    case KIND_RK:       return "rk";
    case KIND_OMEGA:    return "omega";
    case KIND_DELTA_RK: return "delta_rk";
    case KIND_INFERRED: return "inferred";
    case KIND_NONE:     return "none";
    }
    return "unknown";
}

static void emit_kind_manifest(FILE *out, Program *prog) {
    /* Count non-import declarations to decide whether to emit */
    size_t real_count = 0;
    for (size_t i = 0; i < prog->count; i++) {
        if (prog->decls[i]->type != DECL_IMPORT &&
            prog->decls[i]->name.text)
            real_count++;
    }
    if (real_count == 0) return;

    fprintf(out, "\n/* Kind manifest — 256-bit perpendicular encoding metadata */\n");
    fprintf(out, "export const __kindManifest = {\n");

    bool first = true;
    /* De-duplicate by name — relation decls (perpendicular/commensurable) use
     * d->name.text = first dimension name, which collides with the dimension's
     * own entry. */
    char *seen[512] = {0};
    int n_seen = 0;
    for (size_t i = 0; i < prog->count; i++) {
        Decl *d = prog->decls[i];
        if (d->type == DECL_IMPORT) continue;
        if (d->type == DECL_PERPENDICULAR ||
            d->type == DECL_COMMENSURABLE ||
            d->type == DECL_INCOMMENSURABLE) continue;
        if (!d->name.text) continue;
        bool dup = false;
        for (int s = 0; s < n_seen; s++) {
            if (strcmp(seen[s], d->name.text) == 0) { dup = true; break; }
        }
        if (dup) continue;
        if (n_seen < 512) seen[n_seen++] = (char *)d->name.text;
        if (!first) fprintf(out, ",\n");
        fprintf(out, "  '%s': '%s'", d->name.text, kind_id(d->kind));
        first = false;
    }
    fprintf(out, "\n} as const;\n\n");

    fprintf(out, "export type KindOf<K extends keyof typeof __kindManifest>"
                 " = typeof __kindManifest[K];\n");
}

int emit_typescript(Program *prog, FILE *out, DiagList *diags) {
    (void)diags;

    /* M4: set file-scope prog for dispatch wrappers */
    g_ts_prog = prog;

    emit_header(out, prog->filename);

    /* Emit imports first (used-names-only — Sprint 3B) */
    for (size_t i = 0; i < prog->count; i++) {
        if (prog->decls[i]->type == DECL_IMPORT)
            emit_import(out, prog->decls[i], prog);
    }

    /* M4: dispatch via generated switch from ordbok.
     * Replaces hand-written 17-case DeclType switch.
     * Source of truth: ordbok/compiler/compiler_emit_ts_dispatch.szh */
    for (size_t i = 0; i < prog->count; i++) {
        Decl *d = prog->decls[i];
        emit_ts_dispatch(out, d);
    }

    /* Phase 1: emit kind manifest after all declarations */
    emit_kind_manifest(out, prog);

    return 0;
}
