/*
 * suhc — emit_sql.c
 * SQL (PostgreSQL) code generation from .szh declarations.
 *
 * Only dependency declarations produce SQL output.
 * The emitted schema matches the Spoxis migration conventions:
 *   - YYYYMMDDHHMMSS_description.sql naming
 *   - IF NOT EXISTS on index creation
 *   - timestamptz for moments, date for calendar constraints
 *   - RLS policies emitted as comments (manual review required)
 */

#include "emitter.h"
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

/* M5: math function enum + SQL name mappings (generated) */
#include "gen/math_fns.h"
#include "gen/math_fn_sql.h"

/* ------------------------------------------------------------ */
/* Utilities                                                     */
/* ------------------------------------------------------------ */

/* Pluralize a table name: membership → memberships */
static char *pluralize(const char *name) {
    if (!name) return strdup("unknowns");
    size_t len = strlen(name);
    char *out = malloc(len + 4);

    /* Simple English pluralization heuristics */
    if (len > 1 && name[len-1] == 'y' &&
        name[len-2] != 'a' && name[len-2] != 'e' &&
        name[len-2] != 'o' && name[len-2] != 'u') {
        /* dependency → dependencies */
        memcpy(out, name, len - 1);
        strcpy(out + len - 1, "ies");
    } else if (len > 1 && (name[len-1] == 's' || name[len-1] == 'x' ||
               name[len-1] == 'z' ||
               (len > 2 && name[len-2] == 'c' && name[len-1] == 'h') ||
               (len > 2 && name[len-2] == 's' && name[len-1] == 'h'))) {
        /* match → matches */
        sprintf(out, "%ses", name);
    } else {
        sprintf(out, "%ss", name);
    }
    return out;
}

/* ------------------------------------------------------------ */
/* Header                                                        */
/* ------------------------------------------------------------ */

static void emit_sql_header(FILE *out, const char *filename) {
    fprintf(out, "-- Generated by suhc (the suihan compiler) from %s\n",
            filename ? filename : "<stdin>");
    fprintf(out, "-- DO NOT EDIT — regenerate from the .szh source.\n");
    fprintf(out, "--\n");
    fprintf(out, "-- Dependencies are emitted as CREATE TABLE statements.\n");
    fprintf(out, "-- Review and adjust column types before running.\n\n");
}

/* ------------------------------------------------------------ */
/* ξ enum → CHECK constraint values                              */
/* ------------------------------------------------------------ */

/* Collect enum values from ξ declarations for CHECK constraints */
typedef struct {
    char  *name;
    char **values;
    size_t count;
} EnumDef;

typedef struct {
    EnumDef *defs;
    size_t   count;
    size_t   capacity;
} EnumRegistry;

static void er_init(EnumRegistry *er) {
    er->capacity = 16;
    er->defs = calloc(er->capacity, sizeof(EnumDef));
    er->count = 0;
}

static void er_free(EnumRegistry *er) {
    for (size_t i = 0; i < er->count; i++) {
        free(er->defs[i].name);
        for (size_t j = 0; j < er->defs[i].count; j++)
            free(er->defs[i].values[j]);
        free(er->defs[i].values);
    }
    free(er->defs);
}

static void er_add(EnumRegistry *er, const char *name, Expr *val) {
    if (!val || val->type != EXPR_ENUM) return;
    if (er->count >= er->capacity) {
        er->capacity *= 2;
        er->defs = realloc(er->defs, er->capacity * sizeof(EnumDef));
    }
    EnumDef *ed = &er->defs[er->count++];
    ed->name = strdup(name);
    ed->count = val->as.enumeration.count;
    ed->values = malloc(ed->count * sizeof(char *));
    for (size_t i = 0; i < ed->count; i++) {
        ed->values[i] = val->as.enumeration.items[i].name.text ?
            strdup(val->as.enumeration.items[i].name.text) : strdup("");
    }
}

static EnumDef *er_find(EnumRegistry *er, const char *name) {
    for (size_t i = 0; i < er->count; i++) {
        if (strcmp(er->defs[i].name, name) == 0) return &er->defs[i];
    }
    return NULL;
}

/* ------------------------------------------------------------ */
/* dependency → CREATE TABLE                                     */
/* ------------------------------------------------------------ */

static void emit_dependency_sql(FILE *out, Decl *d, EnumRegistry *er) {
    if (!d->name.text) return;

    char *table_name = pluralize(d->name.text);

    /* Extract from/to from arrow expression */
    const char *from_name = NULL;
    const char *to_name = NULL;
    if (d->as.dependency.relation && d->as.dependency.relation->type == EXPR_ARROW) {
        Expr *rel = d->as.dependency.relation;
        if (rel->as.arrow.from && rel->as.arrow.from->type == EXPR_IDENT)
            from_name = rel->as.arrow.from->as.ident.name;
        if (rel->as.arrow.to && rel->as.arrow.to->type == EXPR_IDENT)
            to_name = rel->as.arrow.to->as.ident.name;
    }

    fprintf(out, "-- dependency %s : %s -> %s\n",
            d->name.text,
            from_name ? from_name : "?",
            to_name ? to_name : "?");
    fprintf(out, "CREATE TABLE IF NOT EXISTS %s (\n", table_name);
    fprintf(out, "  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY");

    /* FK for 'from' side */
    if (from_name) {
        if (strcmp(from_name, "user") == 0) {
            fprintf(out, ",\n  user_id uuid NOT NULL REFERENCES profiles(id)");
        } else {
            char *plural = pluralize(from_name);
            fprintf(out, ",\n  %s_id bigint NOT NULL REFERENCES %s(id)", from_name, plural);
            free(plural);
        }
    }

    /* FK for 'to' side */
    if (to_name) {
        if (strcmp(to_name, "user") == 0) {
            fprintf(out, ",\n  target_user_id uuid NOT NULL REFERENCES profiles(id)");
        } else {
            char *plural = pluralize(to_name);
            fprintf(out, ",\n  %s_id bigint NOT NULL REFERENCES %s(id)", to_name, plural);
            free(plural);
        }
    }

    /* Columns from 'carries' field */
    for (size_t i = 0; i < d->as.dependency.field_count; i++) {
        DeclField *f = &d->as.dependency.fields[i];
        if (!f->label.text || strcmp(f->label.text, "carries") != 0) continue;
        if (!f->value) continue;

        /* Handle single ident or list */
        const char *carry_names[16];
        size_t carry_count = 0;

        if (f->value->type == EXPR_IDENT && f->value->as.ident.name) {
            carry_names[carry_count++] = f->value->as.ident.name;
        } else if (f->value->type == EXPR_LIST) {
            for (size_t j = 0; j < f->value->as.list.count && carry_count < 16; j++) {
                Expr *item = f->value->as.list.items[j];
                if (item && item->type == EXPR_IDENT && item->as.ident.name)
                    carry_names[carry_count++] = item->as.ident.name;
            }
        }

        for (size_t c = 0; c < carry_count; c++) {
            const char *carry = carry_names[c];

            if (strcmp(carry, "permission") == 0) {
                /* structural_role with CHECK constraint */
                EnumDef *role_enum = er_find(er, "structural_role");
                fprintf(out, ",\n  structural_role text NOT NULL DEFAULT 'pending'");
                if (role_enum) {
                    fprintf(out, "\n    CHECK (structural_role IN (");
                    for (size_t v = 0; v < role_enum->count; v++) {
                        fprintf(out, "'%s'", role_enum->values[v]);
                        if (v + 1 < role_enum->count) fprintf(out, ", ");
                    }
                    fprintf(out, "))");
                }
                fprintf(out, ",\n  role_types text[]");
            }
            else if (strcmp(carry, "label") == 0) {
                fprintf(out, ",\n  display_title text");
            }
            else if (strcmp(carry, "participation") == 0) {
                fprintf(out, ",\n  status text NOT NULL DEFAULT 'pending'");
            }
            else {
                fprintf(out, ",\n  %s text", carry);
            }
        }
    }

    fprintf(out, ",\n  created_at timestamptz NOT NULL DEFAULT now()");

    /* UNIQUE constraint for the relationship */
    if (from_name && to_name) {
        const char *from_col = strcmp(from_name, "user") == 0 ? "user_id" : from_name;
        const char *to_col = strcmp(to_name, "user") == 0 ? "target_user_id" : to_name;

        /* Build column name strings for UNIQUE */
        fprintf(out, ",\n  UNIQUE (");
        if (strcmp(from_name, "user") == 0) {
            fprintf(out, "user_id");
        } else {
            fprintf(out, "%s_id", from_col);
        }
        fprintf(out, ", ");
        if (strcmp(to_name, "user") == 0) {
            fprintf(out, "target_user_id");
        } else {
            fprintf(out, "%s_id", to_col);
        }
        fprintf(out, ")");
    }

    fprintf(out, "\n);\n\n");

    /* RLS hint */
    fprintf(out, "-- TODO: Enable RLS and create policies for %s\n", table_name);
    fprintf(out, "-- ALTER TABLE %s ENABLE ROW LEVEL SECURITY;\n\n", table_name);

    free(table_name);
}

/* ------------------------------------------------------------ */
/* dimension → ENUM type (optional)                              */
/* ------------------------------------------------------------ */

static void emit_dimension_sql(FILE *out, Decl *d) {
    if (!d->name.text) return;
    Expr *members = d->as.dimension.members;
    if (!members) return;

    fprintf(out, "-- dimension %s\n", d->name.text);
    fprintf(out, "-- Values:");

    if (members->type == EXPR_LIST) {
        for (size_t i = 0; i < members->as.list.count; i++) {
            Expr *item = members->as.list.items[i];
            if (item && item->type == EXPR_IDENT && item->as.ident.name) {
                fprintf(out, " %s", item->as.ident.name);
            }
        }
    }
    fprintf(out, "\n");
    fprintf(out, "-- (Used as CHECK constraint values, not as a SQL ENUM type.\n");
    fprintf(out, "--  Enums in PostgreSQL cannot be extended without migration.)\n\n");
}

/* ------------------------------------------------------------ */
/* projection → SQL function                                     */
/* ------------------------------------------------------------ */

/* Convert snake_case to camelCase for function naming */
static char *sql_fn_name(const char *name) {
    if (!name) return strdup("unknown");
    /* Prefix with resolve_ if not already present */
    const char *prefix = "resolve_";
    if (strncmp(name, "resolve_", 8) == 0) {
        return strdup(name);
    }
    char *out = malloc(strlen(prefix) + strlen(name) + 1);
    sprintf(out, "%s%s", prefix, name);
    return out;
}

static void emit_projection_sql(FILE *out, Decl *d) {
    if (!d->name.text) return;

    char *fn_name = sql_fn_name(d->name.text);

    /* Extract invariant and context field names */
    const char *invariant_name = NULL;
    const char *context_name = NULL;
    const char *yields_name = NULL;
    (void)yields_name;  /* reserved for future use */

    for (size_t i = 0; i < d->as.projection.field_count; i++) {
        DeclField *f = &d->as.projection.fields[i];
        if (!f->label.text) continue;
        if (strcmp(f->label.text, "invariant") == 0) {
            if (f->value && f->value->type == EXPR_IDENT)
                invariant_name = f->value->as.ident.name;
        }
        if (strcmp(f->label.text, "context") == 0) {
            if (f->value && f->value->type == EXPR_IDENT)
                context_name = f->value->as.ident.name;
        }
        if (strcmp(f->label.text, "yields") == 0) {
            if (f->value && f->value->type == EXPR_IDENT)
                yields_name = f->value->as.ident.name;
        }
    }

    fprintf(out, "-- projection %s\n", d->name.text);
    fprintf(out, "CREATE OR REPLACE FUNCTION %s(\n", fn_name);
    fprintf(out, "  p_%s text", invariant_name ? invariant_name : "invariant");
    if (context_name) {
        fprintf(out, ",\n  p_%s text", context_name);
    }
    fprintf(out, "\n) RETURNS text\n");
    fprintf(out, "  LANGUAGE sql\n  IMMUTABLE\nAS $$\n");
    fprintf(out, "  SELECT CASE\n");

    /* Emit case arms */
    for (size_t a = 0; a < d->as.projection.arm_count; a++) {
        ProjectionArm *arm = &d->as.projection.arms[a];
        if (!arm->pattern || !arm->body) continue;

        /* Extract pattern values */
        const char *p1 = NULL, *p2 = NULL;
        if (arm->pattern->type == EXPR_LIST && arm->pattern->as.list.count >= 2) {
            Expr *e1 = arm->pattern->as.list.items[0];
            Expr *e2 = arm->pattern->as.list.items[1];
            if (e1->type == EXPR_IDENT) p1 = e1->as.ident.name;
            if (e1->type == EXPR_WILDCARD) p1 = "_";
            if (e2->type == EXPR_IDENT) p2 = e2->as.ident.name;
            if (e2->type == EXPR_WILDCARD) p2 = "_";
        } else if (arm->pattern->type == EXPR_WILDCARD) {
            p1 = "_"; p2 = "_";
        }

        /* Extract body value */
        const char *result = NULL;
        if (arm->body->type == EXPR_STRING)
            result = arm->body->as.string.value;

        if (!p1 || !result) continue;

        /* Wildcard (_, _) → ELSE */
        if (strcmp(p1, "_") == 0 && p2 && strcmp(p2, "_") == 0) {
            fprintf(out, "    ELSE '%s'\n", result);
            continue;
        }

        /* Build WHEN conditions */
        fprintf(out, "    WHEN ");
        int need_and = 0;
        if (strcmp(p1, "_") != 0) {
            fprintf(out, "p_%s = '%s'", invariant_name ? invariant_name : "invariant", p1);
            need_and = 1;
        }
        if (p2 && strcmp(p2, "_") != 0) {
            if (need_and) fprintf(out, " AND ");
            fprintf(out, "p_%s = '%s'", context_name ? context_name : "context", p2);
        }
        fprintf(out, " THEN '%s'\n", result);
    }

    /* Default fallback if no wildcard arm */
    fprintf(out, "  END\n$$;\n\n");

    free(fn_name);
}

/* ------------------------------------------------------------ */
/* morphism → SQL function stub                                  */
/* ------------------------------------------------------------ */

static void emit_morphism_sql(FILE *out, Decl *d) {
    if (!d->name.text) return;

    const char *from_name = NULL;
    const char *to_name = NULL;
    if (d->as.morphism.signature && d->as.morphism.signature->type == EXPR_ARROW) {
        Expr *rel = d->as.morphism.signature;
        if (rel->as.arrow.from && rel->as.arrow.from->type == EXPR_IDENT)
            from_name = rel->as.arrow.from->as.ident.name;
        if (rel->as.arrow.to && rel->as.arrow.to->type == EXPR_IDENT)
            to_name = rel->as.arrow.to->as.ident.name;
    }

    fprintf(out, "-- morphism %s : %s -> %s\n",
            d->name.text,
            from_name ? from_name : "?",
            to_name ? to_name : "?");
    fprintf(out, "-- TODO: Implement as SECURITY DEFINER function\n");
    fprintf(out, "-- CREATE OR REPLACE FUNCTION %s(p_user_id uuid, p_resource_id bigint)\n",
            d->name.text);
    fprintf(out, "-- RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$\n");
    fprintf(out, "-- BEGIN\n");
    fprintf(out, "--   UPDATE memberships SET structural_role = '%s'\n",
            to_name ? to_name : "?");
    fprintf(out, "--   WHERE user_id = p_user_id AND resource_id = p_resource_id\n");
    fprintf(out, "--     AND structural_role = '%s';\n", from_name ? from_name : "?");
    fprintf(out, "-- END;\n-- $$;\n\n");
}

/* ------------------------------------------------------------ */
/* traversal → PL/pgSQL function                                 */
/* ------------------------------------------------------------ */

/* Simple snake_case to snake_case SQL identifier conversion */
static char *sql_param_name(const char *label) {
    if (!label) return strdup("p_unknown");
    char *out = malloc(strlen(label) + 3);
    sprintf(out, "p_%s", label);
    return out;
}

/* Convert an Expr to a SQL-ish string (simplified, for comments and
 * simple expressions). Full SQL expression compilation is Phase 2B. */
static char *expr_to_sql_str(Expr *e) {
    if (!e) return strdup("NULL");
    switch (e->type) {
    case EXPR_IDENT:
        return e->as.ident.name ? strdup(e->as.ident.name) : strdup("?");
    case EXPR_STRING: {
        char *buf = malloc(strlen(e->as.string.value ? e->as.string.value : "") + 4);
        sprintf(buf, "'%s'", e->as.string.value ? e->as.string.value : "");
        return buf;
    }
    case EXPR_CALL: {
        if (!e->as.call.callee) return strdup("unknown()");
        char *buf = malloc(256);
        int pos = sprintf(buf, "%s(", e->as.call.callee);
        for (size_t i = 0; i < e->as.call.arg_count && pos < 240; i++) {
            if (i > 0) pos += sprintf(buf + pos, ", ");
            char *arg = expr_to_sql_str(e->as.call.args[i]);
            pos += sprintf(buf + pos, "%s", arg);
            free(arg);
        }
        pos += sprintf(buf + pos, ")");
        return buf;
    }
    case EXPR_PIPE_CHAIN: {
        if (e->as.pipe_chain.count == 0) return strdup("NULL");
        /* Emit as nested calls: a |> b |> c → c(b(a)) */
        char *result = expr_to_sql_str(e->as.pipe_chain.stages[0]);
        for (size_t i = 1; i < e->as.pipe_chain.count; i++) {
            char *fn = expr_to_sql_str(e->as.pipe_chain.stages[i]);
            char *buf = malloc(strlen(fn) + strlen(result) + 4);
            sprintf(buf, "%s(%s)", fn, result);
            free(fn); free(result);
            result = buf;
        }
        return result;
    }
    default:
        return strdup("/* expr */");
    }
}

static void emit_traversal_sql(FILE *out, Decl *d) {
    if (!d->name.text) return;

    char *fn_name = sql_fn_name(d->name.text);

    /* Collect section labels and bodies */
    const char *xi_label = NULL, *zeta_label = NULL, *x_label = NULL;
    const char *omega_label = NULL, *delta_label = NULL;
    Expr *rk_expr = NULL, *zeta_expr = NULL, *x_expr = NULL;

    for (size_t i = 0; i < d->as.traversal.section_count; i++) {
        TraversalSection *sec = &d->as.traversal.sections[i];
        switch (sec->section_kind) {
        case KIND_XI:       xi_label = sec->label.text; break;
        case KIND_ZETA:     zeta_label = sec->label.text; zeta_expr = sec->body; break;
        case KIND_X:        x_label = sec->label.text; x_expr = sec->body; break;
        case KIND_RK:       rk_expr = sec->body; break;
        case KIND_OMEGA:    omega_label = sec->label.text; break;
        case KIND_DELTA_RK: delta_label = sec->label.text; break;
        default: break;
        }
    }
    (void)zeta_expr; (void)x_expr;

    /* Header comment */
    fprintf(out, "-- traversal %s\n", d->name.text);
    fprintf(out, "-- Pipeline: %s (ξ)",
            xi_label ? xi_label : "?");
    if (zeta_label) fprintf(out, " × %s (ζ)", zeta_label);
    fprintf(out, " → %s (ω)", omega_label ? omega_label : "?");
    if (delta_label) fprintf(out, " | cast: %s (ΔR.k)", delta_label);
    fprintf(out, "\n");

    fprintf(out, "CREATE OR REPLACE FUNCTION %s(\n", fn_name);

    /* Parameters from section labels */
    bool first_param = true;
    if (xi_label) {
        char *pname = sql_param_name(xi_label);
        fprintf(out, "  %s uuid", pname);
        free(pname);
        first_param = false;
    }
    if (zeta_label) {
        char *pname = sql_param_name(zeta_label);
        fprintf(out, "%s\n  %s text", first_param ? "" : ",", pname);
        free(pname);
        first_param = false;
    }
    if (x_label) {
        char *pname = sql_param_name(x_label);
        fprintf(out, "%s\n  %s bigint[] DEFAULT '{}'", first_param ? "" : ",", pname);
        free(pname);
    }

    fprintf(out, "\n) RETURNS jsonb\n");
    fprintf(out, "  LANGUAGE plpgsql\n  STABLE\n");
    fprintf(out, "AS $$\n");
    fprintf(out, "DECLARE\n  v_result jsonb;\nBEGIN\n");

    /* R.k operator body → CASE statement */
    if (rk_expr && rk_expr->type == EXPR_MATCH) {
        char *disc = rk_expr->as.match_expr.discriminant ?
            strdup(rk_expr->as.match_expr.discriminant->as.ident.name) :
            strdup("?");
        char *pname = sql_param_name(disc);

        fprintf(out, "  CASE %s\n", pname);
        for (size_t a = 0; a < rk_expr->as.match_expr.arm_count; a++) {
            Expr *pat = rk_expr->as.match_expr.arms[a].pattern;
            Expr *body = rk_expr->as.match_expr.arms[a].body;
            char *body_str = body ? expr_to_sql_str(body) : strdup("NULL");

            if (pat && pat->type == EXPR_WILDCARD) {
                fprintf(out, "    ELSE\n");
                fprintf(out, "      -- %s\n", body_str);
                fprintf(out, "      v_result := '[]'::jsonb;\n");
            } else {
                char *pat_str = pat ? expr_to_sql_str(pat) : strdup("?");
                fprintf(out, "    WHEN '%s' THEN\n", pat_str);
                fprintf(out, "      -- %s\n", body_str);
                fprintf(out, "      v_result := '[]'::jsonb; -- TODO: implement\n");
                free(pat_str);
            }
            free(body_str);
        }
        fprintf(out, "  END CASE;\n");
        free(disc);
        free(pname);
    } else if (rk_expr) {
        char *body_str = expr_to_sql_str(rk_expr);
        fprintf(out, "  -- R.k: %s\n", body_str);
        fprintf(out, "  v_result := '[]'::jsonb; -- TODO: implement\n");
        free(body_str);
    } else {
        fprintf(out, "  v_result := '[]'::jsonb;\n");
    }

    fprintf(out, "  RETURN COALESCE(v_result, '[]'::jsonb);\n");
    fprintf(out, "END;\n$$;\n\n");

    free(fn_name);
}

/* ------------------------------------------------------------ */
/* meihua → SQL pure function                                    */
/* ------------------------------------------------------------ */

/* Convert meihua expressions to SQL math — mirrors meihua_expr_to_ts */
static char *meihua_expr_to_sql(Expr *e) {
    if (!e) return strdup("0");

    switch (e->type) {
    case EXPR_CALL: {
        if (!e->as.call.callee) return strdup("0");
        const char *callee = e->as.call.callee;
        /* M5: map math functions via generated enum lookup */
        math_fn_t mfn = math_fn_from_name(callee);
        const char *sql_fn = (mfn != (math_fn_t)-1) ? math_fn_sql(mfn) : NULL;

        /* log2 special case: log2(x) → log(2, x) in PostgreSQL */
        if (mfn == MATH_FN_LOG2 && e->as.call.arg_count == 1) {
            char *arg = meihua_expr_to_sql(e->as.call.args[0]);
            char *buf = malloc(strlen(arg) + 16);
            sprintf(buf, "log(2, %s)", arg);
            free(arg);
            return buf;
        }

        const char *fn = sql_fn ? sql_fn : callee;
        size_t total_len = strlen(fn) + 3;
        char **arg_strs = malloc(e->as.call.arg_count * sizeof(char *));
        for (size_t i = 0; i < e->as.call.arg_count; i++) {
            arg_strs[i] = meihua_expr_to_sql(e->as.call.args[i]);
            total_len += strlen(arg_strs[i]) + 2;
        }
        char *buf = malloc(total_len + 1);
        int pos = sprintf(buf, "%s(", fn);
        for (size_t i = 0; i < e->as.call.arg_count; i++) {
            if (i > 0) pos += sprintf(buf + pos, ", ");
            pos += sprintf(buf + pos, "%s", arg_strs[i]);
            free(arg_strs[i]);
        }
        sprintf(buf + pos, ")");
        free(arg_strs);
        return buf;
    }
    case EXPR_BINARY: {
        char *left = meihua_expr_to_sql(e->as.binary.left);
        char *right = meihua_expr_to_sql(e->as.binary.right);
        const char *op = e->as.binary.op ? e->as.binary.op : "+";
        if (strcmp(op, "^") == 0) {
            char *buf = malloc(strlen(left) + strlen(right) + 16);
            sprintf(buf, "pow(%s, %s)", left, right);
            free(left); free(right);
            return buf;
        }
        /* SQL operator mapping: == → =, != → <> */
        const char *sql_op = op;
        if (strcmp(op, "==") == 0) sql_op = "=";
        else if (strcmp(op, "!=") == 0) sql_op = "<>";
        char *buf = malloc(strlen(left) + strlen(right) + strlen(sql_op) + 8);
        sprintf(buf, "(%s %s %s)", left, sql_op, right);
        free(left); free(right);
        return buf;
    }
    case EXPR_IDENT:
        if (e->as.ident.name) {
            /* Prefix identifiers with p_ for function parameters */
            char *buf = malloc(strlen(e->as.ident.name) + 3);
            sprintf(buf, "p_%s", e->as.ident.name);
            return buf;
        }
        return strdup("0");
    case EXPR_NUMBER:
        if (e->as.number.text) return strdup(e->as.number.text);
        return strdup("0");
    case EXPR_UNARY: {
        char *operand = meihua_expr_to_sql(e->as.unary.operand);
        const char *op = e->as.unary.op ? e->as.unary.op : "-";
        char *buf = malloc(strlen(operand) + strlen(op) + 4);
        sprintf(buf, "(%s%s)", op, operand);
        free(operand);
        return buf;
    }
    case EXPR_IF: {
        char *cond = meihua_expr_to_sql(e->as.if_expr.condition);
        char *then_b = meihua_expr_to_sql(e->as.if_expr.then_branch);
        char *else_b = meihua_expr_to_sql(e->as.if_expr.else_branch);
        char *buf = malloc(strlen(cond) + strlen(then_b) + strlen(else_b) + 40);
        sprintf(buf, "CASE WHEN %s THEN %s ELSE %s END", cond, then_b, else_b);
        free(cond); free(then_b); free(else_b);
        return buf;
    }
    case EXPR_COALESCE: {
        char *left = meihua_expr_to_sql(e->as.coalesce.left);
        char *right = meihua_expr_to_sql(e->as.coalesce.right);
        char *buf = malloc(strlen(left) + strlen(right) + 16);
        sprintf(buf, "COALESCE(%s, %s)", left, right);
        free(left); free(right);
        return buf;
    }
    case EXPR_STRING: {
        const char *val = e->as.string.value ? e->as.string.value : "";
        char *buf = malloc(strlen(val) + 4);
        sprintf(buf, "'%s'", val);
        return buf;
    }
    case EXPR_LIST: {
        size_t total = 8; /* ARRAY[] */
        char **items = malloc(e->as.list.count * sizeof(char *));
        for (size_t i = 0; i < e->as.list.count; i++) {
            items[i] = meihua_expr_to_sql(e->as.list.items[i]);
            total += strlen(items[i]) + 2;
        }
        char *buf = malloc(total + 1);
        int pos = sprintf(buf, "ARRAY[");
        for (size_t i = 0; i < e->as.list.count; i++) {
            if (i > 0) pos += sprintf(buf + pos, ", ");
            pos += sprintf(buf + pos, "%s", items[i]);
            free(items[i]);
        }
        sprintf(buf + pos, "]");
        free(items);
        return buf;
    }
    case EXPR_MATCH: {
        /* match discriminant { pat -> body, ... } → CASE disc WHEN pat THEN body ... END */
        char *disc = meihua_expr_to_sql(e->as.match_expr.discriminant);
        size_t total = strlen(disc) + 16; /* CASE ... END */
        char **whens = malloc(e->as.match_expr.arm_count * sizeof(char *));
        for (size_t i = 0; i < e->as.match_expr.arm_count; i++) {
            char *body = meihua_expr_to_sql(e->as.match_expr.arms[i].body);
            Expr *pat = e->as.match_expr.arms[i].pattern;
            if (pat && pat->type == EXPR_WILDCARD) {
                size_t len = strlen(body) + 8;
                whens[i] = malloc(len + 1);
                sprintf(whens[i], " ELSE %s", body);
            } else {
                /* Pattern idents are literal match values, not parameters.
                 * Emit as SQL string literals (not p_-prefixed). */
                char *pstr;
                if (pat && pat->type == EXPR_IDENT && pat->as.ident.name) {
                    pstr = malloc(strlen(pat->as.ident.name) + 4);
                    sprintf(pstr, "'%s'", pat->as.ident.name);
                } else if (pat && pat->type == EXPR_NUMBER && pat->as.number.text) {
                    pstr = strdup(pat->as.number.text);
                } else if (pat && pat->type == EXPR_STRING && pat->as.string.value) {
                    pstr = malloc(strlen(pat->as.string.value) + 4);
                    sprintf(pstr, "'%s'", pat->as.string.value);
                } else {
                    pstr = meihua_expr_to_sql(pat);
                }
                size_t len = strlen(pstr) + strlen(body) + 16;
                whens[i] = malloc(len + 1);
                sprintf(whens[i], " WHEN %s THEN %s", pstr, body);
                free(pstr);
            }
            total += strlen(whens[i]);
            free(body);
        }
        char *buf = malloc(total + 1);
        int pos = sprintf(buf, "CASE %s", disc);
        for (size_t i = 0; i < e->as.match_expr.arm_count; i++) {
            pos += sprintf(buf + pos, "%s", whens[i]);
            free(whens[i]);
        }
        sprintf(buf + pos, " END");
        free(whens);
        free(disc);
        return buf;
    }
    default:
        return strdup("/* expr */");
    }
}

static void emit_meihua_sql(FILE *out, Decl *d) {
    if (!d->name.text) return;

    fprintf(out, "-- meihua %s — pure computation\n", d->name.text);
    fprintf(out, "CREATE OR REPLACE FUNCTION %s(\n", d->name.text);

    for (size_t i = 0; i < d->as.exec_layer.param_count; i++) {
        if (d->as.exec_layer.params[i].text) {
            fprintf(out, "  p_%s double precision", d->as.exec_layer.params[i].text);
            if (i + 1 < d->as.exec_layer.param_count) fprintf(out, ",\n");
        }
    }

    fprintf(out, "\n) RETURNS double precision\n");
    fprintf(out, "  LANGUAGE sql\n  IMMUTABLE\n");
    fprintf(out, "AS $$\n");

    Expr *body = d->as.exec_layer.body;
    /* Unwrap single-statement blocks */
    if (body && body->type == EXPR_BLOCK && body->as.block.count == 1) {
        body = body->as.block.stmts[0];
    }
    if (body) {
        char *sql = meihua_expr_to_sql(body);
        fprintf(out, "  SELECT %s\n", sql);
        free(sql);
    } else {
        fprintf(out, "  SELECT 0 -- no body captured\n");
    }

    fprintf(out, "$$;\n\n");
}

/* ------------------------------------------------------------ */
/* songqiao → SQL config function returning jsonb                */
/* ------------------------------------------------------------ */

static void emit_songqiao_sql(FILE *out, Decl *d) {
    if (!d->name.text) return;

    fprintf(out, "-- songqiao %s — runtime landscape configuration\n", d->name.text);
    fprintf(out, "CREATE OR REPLACE FUNCTION songqiao_%s(\n", d->name.text);

    for (size_t i = 0; i < d->as.exec_layer.param_count; i++) {
        if (d->as.exec_layer.params[i].text) {
            fprintf(out, "  p_%s text", d->as.exec_layer.params[i].text);
            if (i + 1 < d->as.exec_layer.param_count) fprintf(out, ",\n");
        }
    }

    fprintf(out, "\n) RETURNS jsonb\n");
    fprintf(out, "  LANGUAGE sql\n  IMMUTABLE\n");
    fprintf(out, "AS $$\n");

    Expr *body = d->as.exec_layer.body;
    if (body && body->type == EXPR_BLOCK && body->as.block.count == 1) {
        body = body->as.block.stmts[0];
    }
    if (body) {
        char *sql = meihua_expr_to_sql(body);
        fprintf(out, "  SELECT to_jsonb(%s)\n", sql);
        free(sql);
    } else {
        fprintf(out, "  SELECT '{}'::jsonb\n");
    }

    fprintf(out, "$$;\n\n");
}

/* ------------------------------------------------------------ */
/* M4: dispatch wrappers — uniform (FILE*, Decl*) signature      */
/* ------------------------------------------------------------ */

/* File-scope EnumRegistry pointer for dependency dispatch wrapper */
static EnumRegistry *g_sql_er;

static void emit_dependency_sql_d(FILE *out, Decl *d) {
    emit_dependency_sql(out, d, g_sql_er);
}
static void emit_unit_sql_comment(FILE *out, Decl *d) {
    fprintf(out, "-- unit %s (structural — no SQL output)\n\n",
            d->name.text ? d->name.text : "?");
}
static void emit_import_sql_comment(FILE *out, Decl *d) {
    fprintf(out, "-- import %s\n",
            d->as.import_decl.module_name ?
            d->as.import_decl.module_name : "?");
}

/* M4: generated dispatch — replaces hand-written switch in emit_sql().
 * Source of truth: ordbok/compiler/compiler_emit_sql_dispatch.szh */
#include "gen/emit_sql_dispatch.h"

/* ------------------------------------------------------------ */
/* Public API                                                    */
/* ------------------------------------------------------------ */

/* ------------------------------------------------------------ */
/* Kind metadata table — preserves kind info in SQL output       */
/* ------------------------------------------------------------ */

static const char *sql_kind_str(Kind k) {
    switch (k) {
    case KIND_XI:       return "xi";
    case KIND_ZETA:     return "zeta";
    case KIND_X:        return "x";
    case KIND_RK:       return "rk";
    case KIND_OMEGA:    return "omega";
    case KIND_DELTA_RK: return "delta_rk";
    case KIND_INFERRED: return "inferred";
    case KIND_NONE:     return "none";
    }
    return "unknown";
}

static void emit_kind_metadata_table(FILE *out, Program *prog) {
    /* Count non-import declarations */
    size_t real_count = 0;
    for (size_t i = 0; i < prog->count; i++) {
        if (prog->decls[i]->type != DECL_IMPORT &&
            prog->decls[i]->name.text)
            real_count++;
    }
    if (real_count == 0) return;

    fprintf(out, "\n-- Kind metadata (256-bit perpendicular encoding)\n");
    fprintf(out, "CREATE TABLE IF NOT EXISTS _szh_kind_metadata (\n");
    fprintf(out, "  symbol_name  text PRIMARY KEY,\n");
    fprintf(out, "  kind         text NOT NULL,\n");
    fprintf(out, "  source_file  text,\n");
    fprintf(out, "  updated_at   timestamptz DEFAULT now()\n");
    fprintf(out, ");\n\n");

    for (size_t i = 0; i < prog->count; i++) {
        Decl *d = prog->decls[i];
        if (d->type == DECL_IMPORT) continue;
        if (!d->name.text) continue;

        fprintf(out,
            "INSERT INTO _szh_kind_metadata (symbol_name, kind, source_file)\n"
            "VALUES ('%s', '%s', '%s')\n"
            "ON CONFLICT (symbol_name) DO UPDATE SET\n"
            "  kind = EXCLUDED.kind,\n"
            "  source_file = EXCLUDED.source_file,\n"
            "  updated_at = now();\n\n",
            d->name.text,
            sql_kind_str(d->kind),
            prog->filename ? prog->filename : "<stdin>");
    }
}

int emit_sql(Program *prog, FILE *out, DiagList *diags) {
    (void)diags;

    emit_sql_header(out, prog->filename);

    /* First pass: collect ξ enums for CHECK constraints */
    EnumRegistry er;
    er_init(&er);

    /* Collect from imported programs first */
    size_t imp_count = 0;
    Decl **imp_decls = collect_imported_decls(prog, &imp_count);
    for (size_t i = 0; i < imp_count; i++) {
        Decl *d = imp_decls[i];
        if (d->type == DECL_KINDED_VALUE && d->kind == KIND_XI &&
            d->as.kinded.value && d->as.kinded.value->type == EXPR_ENUM &&
            d->name.text) {
            er_add(&er, d->name.text, d->as.kinded.value);
        }
    }
    free(imp_decls);

    /* Collect from local declarations */
    for (size_t i = 0; i < prog->count; i++) {
        Decl *d = prog->decls[i];
        if (d->type == DECL_KINDED_VALUE && d->kind == KIND_XI &&
            d->as.kinded.value && d->as.kinded.value->type == EXPR_ENUM &&
            d->name.text) {
            er_add(&er, d->name.text, d->as.kinded.value);
        }
    }

    /* M4: set file-scope er for dispatch wrappers */
    g_sql_er = &er;

    /* M4: dispatch via generated switch from ordbok.
     * Replaces hand-written 12-case DeclType switch.
     * Source of truth: ordbok/compiler/compiler_emit_sql_dispatch.szh */
    for (size_t i = 0; i < prog->count; i++) {
        Decl *d = prog->decls[i];
        emit_sql_dispatch(out, d);
    }

    /* Phase 1: emit kind metadata table after all declarations */
    emit_kind_metadata_table(out, prog);

    er_free(&er);
    return 0;
}
