/*
 * Generated by suhc (the suihan compiler) from ordbok/compiler/compiler_kind_names.szh
 * DO NOT EDIT — regenerate from the .szh source.
 *
 * This is a self-contained C11 header.
 * Include it in exactly one translation unit, or use
 * static inline functions (already the default).
 */

#ifndef SUHC_GEN_COMPILER_KIND_NAMES_SZH
#define SUHC_GEN_COMPILER_KIND_NAMES_SZH

#include <math.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>

/* import compiler_kinds */
/* projection kind_name */
static inline const char *resolve_kind_name(
    const char *kind
) {
    return "";
}

#endif /* SUHC_GEN_COMPILER_KIND_NAMES_SZH */
