/*
 * Generated by suhc (the suihan compiler) from ordbok/compiler/compiler_kinds.szh
 * DO NOT EDIT — regenerate from the .szh source.
 *
 * This is a self-contained C11 header.
 * Include it in exactly one translation unit, or use
 * static inline functions (already the default).
 */

#ifndef SUHC_GEN_COMPILER_KINDS_SZH
#define SUHC_GEN_COMPILER_KINDS_SZH

#include <math.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>

/* dimension kind */
typedef enum {
    KIND_XI,
    KIND_ZETA,
    KIND_X,
    KIND_RK,
    KIND_OMEGA,
    KIND_DELTA_RK,
    KIND_INFERRED,
    KIND_NONE
} kind_t;

static inline const char *kind_to_str(kind_t val) {
    switch (val) {
    case KIND_XI: return "xi";
    case KIND_ZETA: return "zeta";
    case KIND_X: return "x";
    case KIND_RK: return "rk";
    case KIND_OMEGA: return "omega";
    case KIND_DELTA_RK: return "delta_rk";
    case KIND_INFERRED: return "inferred";
    case KIND_NONE: return "none";
    }
    return "unknown";
}

#endif /* SUHC_GEN_COMPILER_KINDS_SZH */
