/*
 * Generated by suhc (the suihan compiler) from ordbok/compiler/compiler_emit_c_dispatch.szh
 * DO NOT EDIT — regenerate from the .szh source.
 *
 * This is a self-contained C11 header.
 * Include it in exactly one translation unit, or use
 * static inline functions (already the default).
 */

#ifndef SUHC_GEN_COMPILER_EMIT_C_DISPATCH_SZH
#define SUHC_GEN_COMPILER_EMIT_C_DISPATCH_SZH

#include <math.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>

/* import compiler_decl_types */
/* projection emit_c_dispatch (enum switch over decl) */
static inline const char *emit_c_dispatch(decl_t val) {
    switch (val) {
    case DECL_DIMENSION: return "emit_c_dimension";
    case DECL_DEPENDENCY: return "emit_c_dependency";
    case DECL_PROJECTION: return "emit_c_projection";
    case DECL_MORPHISM: return "emit_c_morphism";
    case DECL_TRAVERSAL: return "emit_c_traversal";
    case DECL_MEIHUA: return "emit_c_meihua";
    case DECL_ZHULIN: return "emit_c_zhulin";
    case DECL_SONGQIAO: return "emit_c_songqiao";
    case DECL_UNIT: return "emit_c_unit";
    case DECL_MAGNITUDE: return "emit_c_magnitude";
    case DECL_VECTOR: return "emit_c_vector";
    case DECL_KINDED_VALUE: return "emit_c_kinded_value";
    case DECL_INCOMMENSURABLE: return "";
    case DECL_COMMENSURABLE: return "";
    case DECL_PERPENDICULAR: return "";
    case DECL_IMPORT: return "emit_c_import_comment";
    case DECL_ZERO: return "";
    case DECL_CONTAINMENT: return "";
    }
    return "<unknown>";
}

#endif /* SUHC_GEN_COMPILER_EMIT_C_DISPATCH_SZH */
